<?php

/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateOperation;

/**
 * @internal
 */
class CRSTransformationsAntarctic
{
    protected static array $sridData = [
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1890',
            'name' => 'Australian Antarctic to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4176',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19992',
            'name' => 'Antarctic Polar Stereographic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3031',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19993',
            'name' => 'Australian Antarctic Polar Stereographic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3032',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19994',
            'name' => 'Australian Antarctic Lambert',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3033',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17204',
            'name' => 'SCAR IMW SP19-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3204',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17205',
            'name' => 'SCAR IMW SP21-22',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3205',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17206',
            'name' => 'SCAR IMW SP23-24',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3206',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17207',
            'name' => 'SCAR IMW SQ01-02',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3207',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17208',
            'name' => 'SCAR IMW SQ19-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3208',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17209',
            'name' => 'SCAR IMW SQ21-22',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3209',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17210',
            'name' => 'SCAR IMW SQ37-38',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3210',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17211',
            'name' => 'SCAR IMW SQ39-40',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3211',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17212',
            'name' => 'SCAR IMW SQ41-42',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3212',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17213',
            'name' => 'SCAR IMW SQ43-44',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3213',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17214',
            'name' => 'SCAR IMW SQ45-46',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3214',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17215',
            'name' => 'SCAR IMW SQ47-48',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3215',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17216',
            'name' => 'SCAR IMW SQ49-50',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3216',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17217',
            'name' => 'SCAR IMW SQ51-52',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3217',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17218',
            'name' => 'SCAR IMW SQ53-54',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3218',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17219',
            'name' => 'SCAR IMW SQ55-56',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3219',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17220',
            'name' => 'SCAR IMW SQ57-58',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3220',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17221',
            'name' => 'SCAR IMW SR13-14',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3221',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17222',
            'name' => 'SCAR IMW SR15-16',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3222',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17223',
            'name' => 'SCAR IMW SR17-18',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3223',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17224',
            'name' => 'SCAR IMW SR19-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3224',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17225',
            'name' => 'SCAR IMW SR27-28',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3225',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17226',
            'name' => 'SCAR IMW SR29-30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3226',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17227',
            'name' => 'SCAR IMW SR31-32',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3227',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17228',
            'name' => 'SCAR IMW SR33-34',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3228',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17229',
            'name' => 'SCAR IMW SR35-36',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3229',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17230',
            'name' => 'SCAR IMW SR37-38',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3230',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17231',
            'name' => 'SCAR IMW SR39-40',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3231',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17232',
            'name' => 'SCAR IMW SR41-42',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3232',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17233',
            'name' => 'SCAR IMW SR43-44',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3233',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17234',
            'name' => 'SCAR IMW SR45-46',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3234',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17235',
            'name' => 'SCAR IMW SR47-48',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3235',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17236',
            'name' => 'SCAR IMW SR49-50',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3236',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17237',
            'name' => 'SCAR IMW SR51-52',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3237',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17238',
            'name' => 'SCAR IMW SR53-54',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3238',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17239',
            'name' => 'SCAR IMW SR55-56',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3239',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17240',
            'name' => 'SCAR IMW SR57-58',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3240',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17241',
            'name' => 'SCAR IMW SR59-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3241',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17242',
            'name' => 'SCAR IMW SS04-06',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3242',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17243',
            'name' => 'SCAR IMW SS07-09',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3243',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17244',
            'name' => 'SCAR IMW SS10-12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3244',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17245',
            'name' => 'SCAR IMW SS13-15',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3245',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17246',
            'name' => 'SCAR IMW SS16-18',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3246',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17247',
            'name' => 'SCAR IMW SS19-21',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3247',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17248',
            'name' => 'SCAR IMW SS25-27',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3248',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17249',
            'name' => 'SCAR IMW SS28-30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3249',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17250',
            'name' => 'SCAR IMW SS31-33',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3250',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17251',
            'name' => 'SCAR IMW SS34-36',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3251',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17252',
            'name' => 'SCAR IMW SS37-39',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3252',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17253',
            'name' => 'SCAR IMW SS40-42',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3253',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17254',
            'name' => 'SCAR IMW SS43-45',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3254',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17255',
            'name' => 'SCAR IMW SS46-48',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3255',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17256',
            'name' => 'SCAR IMW SS49-51',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3256',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17257',
            'name' => 'SCAR IMW SS52-54',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3257',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17258',
            'name' => 'SCAR IMW SS55-57',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3258',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17259',
            'name' => 'SCAR IMW SS58-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3259',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17260',
            'name' => 'SCAR IMW ST01-04',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3260',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17261',
            'name' => 'SCAR IMW ST05-08',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3261',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17262',
            'name' => 'SCAR IMW ST09-12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3262',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17263',
            'name' => 'SCAR IMW ST13-16',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3263',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17264',
            'name' => 'SCAR IMW ST17-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3264',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17265',
            'name' => 'SCAR IMW ST21-24',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3265',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17266',
            'name' => 'SCAR IMW ST25-28',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3266',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17267',
            'name' => 'SCAR IMW ST29-32',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3267',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17268',
            'name' => 'SCAR IMW ST33-36',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3268',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17269',
            'name' => 'SCAR IMW ST37-40',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3269',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17270',
            'name' => 'SCAR IMW ST41-44',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3270',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17271',
            'name' => 'SCAR IMW ST45-48',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3271',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17272',
            'name' => 'SCAR IMW ST49-52',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3272',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17273',
            'name' => 'SCAR IMW ST53-56',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3273',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17274',
            'name' => 'SCAR IMW ST57-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3274',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17275',
            'name' => 'SCAR IMW SU01-05',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3275',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17276',
            'name' => 'SCAR IMW SU06-10',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3276',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17277',
            'name' => 'SCAR IMW SU11-15',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3277',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17278',
            'name' => 'SCAR IMW SU16-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3278',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17279',
            'name' => 'SCAR IMW SU21-25',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3279',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17280',
            'name' => 'SCAR IMW SU26-30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3280',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17281',
            'name' => 'SCAR IMW SU31-35',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3281',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17282',
            'name' => 'SCAR IMW SU36-40',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3282',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17283',
            'name' => 'SCAR IMW SU41-45',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3283',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17284',
            'name' => 'SCAR IMW SU46-50',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3284',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17285',
            'name' => 'SCAR IMW SU51-55',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3285',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17286',
            'name' => 'SCAR IMW SU56-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3286',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17287',
            'name' => 'SCAR IMW SV01-10',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3287',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17288',
            'name' => 'SCAR IMW SV11-20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3288',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17289',
            'name' => 'SCAR IMW SV21-30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3289',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17290',
            'name' => 'SCAR IMW SV31-40',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3290',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17291',
            'name' => 'SCAR IMW SV41-50',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3291',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17292',
            'name' => 'SCAR IMW SV51-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3292',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17293',
            'name' => 'SCAR IMW SW01-60',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3293',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17294',
            'name' => 'USGS Transantarctic Mountains',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3294',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19854',
            'name' => 'South Georgia Lambert',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3762',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19983',
            'name' => 'Terre Adelie Polar Stereographic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4636',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2985',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1921',
            'name' => 'Petrels 1972 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4636',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19983',
            'name' => 'Terre Adelie Polar Stereographic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4637',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2986',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1922',
            'name' => 'Perroud 1950 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4637',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7083',
            'name' => 'Perroud 1950 to RGTAAF07 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4637',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7073',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15802',
            'name' => 'Camp Area Astro to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4715',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 999.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15813',
            'name' => 'South Georgia 1968 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4722',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15812',
            'name' => 'Deception Island to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4736',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 35.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17966',
            'name' => 'Darwin Glacier Lambert Conformal 2000',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3852',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15974',
            'name' => 'RSRGD2000 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5475',
            'name' => 'McMurdo Sound Lambert Conformal 2000',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5479',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5476',
            'name' => 'Borchgrevink Coast Lambert Conformal 2000',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5480',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5477',
            'name' => 'Pennell Coast Lambert Conformal 2000',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5481',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5478',
            'name' => 'Ross Sea Polar Stereographic 2000',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4764',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5482',
            'accuracy' => 0,
        ],
    ];

    public static function getSupportedTransformations(): array
    {
        return static::$sridData;
    }
}
