<?php

/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateOperation;

/**
 * @internal
 */
class CRSTransformationsAfrica
{
    protected static array $sridData = [
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10264',
            'name' => 'RGSH2020 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::10299',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17412',
            'name' => 'Congo Transverse Mercator zone 12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4048',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17414',
            'name' => 'Congo Transverse Mercator zone 14',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4049',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17416',
            'name' => 'Congo Transverse Mercator zone 16',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4050',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17418',
            'name' => 'Congo Transverse Mercator zone 18',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4051',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17420',
            'name' => 'Congo Transverse Mercator zone 20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4056',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17422',
            'name' => 'Congo Transverse Mercator zone 22',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4057',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17424',
            'name' => 'Congo Transverse Mercator zone 24',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4058',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17426',
            'name' => 'Congo Transverse Mercator zone 26',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4059',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17428',
            'name' => 'Congo Transverse Mercator zone 28',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4060',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17430',
            'name' => 'Congo Transverse Mercator zone 30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5844',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1298',
            'name' => 'Tete to Moznet (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4127',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4130',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1299',
            'name' => 'Tete to Moznet (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4127',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4130',
            'accuracy' => 4.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1300',
            'name' => 'Tete to Moznet (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4127',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4130',
            'accuracy' => 3.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1301',
            'name' => 'Tete to Moznet (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4127',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4130',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6900',
            'name' => 'Observatario to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4129',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1302',
            'name' => 'Moznet to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4130',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17005',
            'name' => 'TM 5 NW',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4142',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2164',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1469',
            'name' => 'Locodjo 1965 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4142',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17005',
            'name' => 'TM 5 NW',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4143',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2165',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1470',
            'name' => 'Abidjan 1987 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4143',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17515',
            'name' => 'South African Survey Grid zone 15',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2046',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17517',
            'name' => 'South African Survey Grid zone 17',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2047',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17519',
            'name' => 'South African Survey Grid zone 19',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2048',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17521',
            'name' => 'South African Survey Grid zone 21',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2049',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17523',
            'name' => 'South African Survey Grid zone 23',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2050',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17525',
            'name' => 'South African Survey Grid zone 25',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2051',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17527',
            'name' => 'South African Survey Grid zone 27',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2052',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17529',
            'name' => 'South African Survey Grid zone 29',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2053',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17531',
            'name' => 'South African Survey Grid zone 31',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2054',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17533',
            'name' => 'South African Survey Grid zone 33',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2055',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1505',
            'name' => 'Hartebeesthoek94 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9219',
            'name' => 'South Africa Basic Survey Unit Albers 25E',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9221',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9220',
            'name' => 'South Africa Basic Survey Unit Albers 44E',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9222',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1518',
            'name' => 'Dabola 1981 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4155',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 25.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18240',
            'name' => 'Libya zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2068',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18241',
            'name' => 'Libya zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2069',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18242',
            'name' => 'Libya zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2070',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18243',
            'name' => 'Libya zone 8',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2071',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18244',
            'name' => 'Libya zone 9',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2072',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18245',
            'name' => 'Libya zone 10',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2073',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18246',
            'name' => 'Libya zone 11',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2074',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18247',
            'name' => 'Libya zone 12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2075',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18248',
            'name' => 'Libya zone 13',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2076',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16412',
            'name' => 'TM 12 NE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2087',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15707',
            'name' => 'ELD79 to WGS 84 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15778',
            'name' => 'ELD79 to WGS 84 (7)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15909',
            'name' => 'ELD79 to WGS 84 (8)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15923',
            'name' => 'ELD79 to WGS 84 (9)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1860',
            'name' => 'ELD79 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1862',
            'name' => 'ELD79 to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15924',
            'name' => 'ELD79 to LGD2006 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4159',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1547',
            'name' => 'Bissau to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4165',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 25.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19959',
            'name' => 'Ghana National Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4168',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2136',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17001',
            'name' => 'TM 1 NW',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4168',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2137',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1570',
            'name' => 'Accra to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4168',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 25.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6896',
            'name' => 'Accra to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4168',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 6.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19963',
            'name' => 'Sierra Leone New Colony Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4174',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2159',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19964',
            'name' => 'New War Office Sierra Leone Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4174',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2160',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1614',
            'name' => 'Sierra Leone 1968 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4175',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18415',
            'name' => 'French Equatorial Africa west zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4192',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3119',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15873',
            'name' => 'Douala 1948 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4192',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1902',
            'name' => 'Manoca 1962 to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4193',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1796',
            'name' => 'Manoca 1962 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4193',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1805',
            'name' => 'Garoua to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4197',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1806',
            'name' => 'Kousseri to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4198',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1100',
            'name' => 'Adindan to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 9.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1101',
            'name' => 'Adindan to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1102',
            'name' => 'Adindan to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1103',
            'name' => 'Adindan to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 6.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1104',
            'name' => 'Adindan to WGS 84 (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1105',
            'name' => 'Adindan to WGS 84 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1106',
            'name' => 'Adindan to WGS 84 (7)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4201',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 7.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1107',
            'name' => 'Afgooye to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4205',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1114',
            'name' => 'Arc 1950 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 7.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1116',
            'name' => 'Arc 1950 to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1117',
            'name' => 'Arc 1950 to WGS 84 (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 27.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1118',
            'name' => 'Arc 1950 to WGS 84 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1120',
            'name' => 'Arc 1950 to WGS 84 (8)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 41.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6904',
            'name' => 'Arc 1950 to WGS 84 (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 29.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6906',
            'name' => 'Arc 1950 to WGS 84 (10)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4209',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1122',
            'name' => 'Arc 1960 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4210',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 35.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1284',
            'name' => 'Arc 1960 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4210',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 6.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1285',
            'name' => 'Arc 1960 to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4210',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3998',
            'name' => 'Arc 1960 to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4210',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 35.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16413',
            'name' => 'TM 13 NE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4213',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2931',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1839',
            'name' => 'Beduaram to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4213',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15849',
            'name' => 'Beduaram to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4213',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16611',
            'name' => 'TM 11.30 SE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4220',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22091',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16612',
            'name' => 'TM 12 SE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4220',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22092',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1317',
            'name' => 'Camacupa 1948 to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4220',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9904',
            'name' => 'Camacupa 1948 to RSAO13 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4220',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'accuracy' => 8.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9905',
            'name' => 'Camacupa 1948 to RSAO13 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4220',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17515',
            'name' => 'South African Survey Grid zone 15',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22275',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17517',
            'name' => 'South African Survey Grid zone 17',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22277',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17519',
            'name' => 'South African Survey Grid zone 19',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22279',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17521',
            'name' => 'South African Survey Grid zone 21',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22281',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17523',
            'name' => 'South African Survey Grid zone 23',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22283',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17525',
            'name' => 'South African Survey Grid zone 25',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22285',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17527',
            'name' => 'South African Survey Grid zone 27',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22287',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17529',
            'name' => 'South African Survey Grid zone 29',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22289',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17531',
            'name' => 'South African Survey Grid zone 31',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22291',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17533',
            'name' => 'South African Survey Grid zone 33',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22293',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1504',
            'name' => 'Cape to Hartebeesthoek94 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4148',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1129',
            'name' => 'Cape to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4222',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16411',
            'name' => 'TM 11 NE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4223',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2088',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18181',
            'name' => 'Nord Tunisie',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4223',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22391',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18182',
            'name' => 'Sud Tunisie',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4223',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22392',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1130',
            'name' => 'Carthage to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4223',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 14.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18071',
            'name' => 'Egypt Blue Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22991',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18072',
            'name' => 'Egypt Red Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22992',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18073',
            'name' => 'Egypt Purple Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22993',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18074',
            'name' => 'Egypt Extended Purple Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22994',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1545',
            'name' => 'Egypt 1907 to WGS 72 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4322',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7697',
            'name' => 'Egypt 1907 to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4229',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.2,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1137',
            'name' => 'ED50 to WGS 84 (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4230',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 13.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1245',
            'name' => 'ED50 to WGS 84 (16)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4230',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1810',
            'name' => 'ED50 to WGS 84 (31)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4230',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19904',
            'name' => 'Ghana Metre Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4250',
            'target_crs' => 'urn:ogc:def:crs:EPSG::25000',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1159',
            'name' => 'Leigon to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4250',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1160',
            'name' => 'Liberia 1964 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4251',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1164',
            'name' => 'Mahe 1971 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4256',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1557',
            'name' => 'Malongo 1987 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4259',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9906',
            'name' => 'Malongo 1987 to RSAO13 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4259',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18131',
            'name' => 'Nord Maroc',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4261',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26191',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18132',
            'name' => 'Sud Maroc',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4261',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26192',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18134',
            'name' => 'Sahara Nord',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4261',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26194',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18135',
            'name' => 'Sahara Sud',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4261',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26195',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1166',
            'name' => 'Merchich to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4261',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 7.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1165',
            'name' => 'Massawa to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4262',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18151',
            'name' => 'Nigeria West Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26391',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18152',
            'name' => 'Nigeria Mid Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26392',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18153',
            'name' => 'Nigeria East Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::26393',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1167',
            'name' => 'Minna to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1168',
            'name' => 'Minna to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1754',
            'name' => 'Minna to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4263',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1532',
            'name' => 'M\'poraloko to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4266',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1200',
            'name' => 'Pointe Noire to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4282',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1802',
            'name' => 'Pointe Noire to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4282',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.15,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17611',
            'name' => 'South West African Survey Grid zone 11',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29371',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17613',
            'name' => 'South West African Survey Grid zone 13',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29373',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17615',
            'name' => 'South West African Survey Grid zone 15',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29375',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17617',
            'name' => 'South West African Survey Grid zone 17',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29377',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17619',
            'name' => 'South West African Survey Grid zone 19',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29379',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17621',
            'name' => 'South West African Survey Grid zone 21',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29381',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17623',
            'name' => 'South West African Survey Grid zone 23',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29383',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17625',
            'name' => 'South West African Survey Grid zone 25',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29385',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1271',
            'name' => 'Schwarzeck to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4293',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 999.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6873',
            'name' => 'Tananarive to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4297',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 3.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8440',
            'name' => 'Laborde Grid (Greenwich)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4297',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8441',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18011',
            'name' => 'Nord Algerie (ancienne)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4304',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30491',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18012',
            'name' => 'Sud Algerie (ancienne)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4304',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30492',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1294',
            'name' => 'Voirol 1875 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4304',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 999.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18021',
            'name' => 'Nord Algerie',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4307',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30791',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18022',
            'name' => 'Sud Algerie',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4307',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30792',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1560',
            'name' => 'Nord Sahara 1959 to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4307',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 8.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10296',
            'name' => 'Nord Sahara 1959 to WGS 84 (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4307',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1828',
            'name' => 'Yoff to WGS 72 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4310',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4322',
            'accuracy' => 25.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6903',
            'name' => 'Yoff to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4310',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1517',
            'name' => 'Conakry 1905 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4315',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 30.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16636',
            'name' => 'TM 36 SE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::32766',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4825',
            'name' => 'Cape Verde National',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4826',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5222',
            'name' => 'Gabon Transverse Mercator',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5223',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5522',
            'name' => 'Gabon Transverse Mercator 2011',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5523',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16612',
            'name' => 'TM 12 SE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5842',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4476',
            'name' => 'RGM04 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4470',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4478',
            'name' => 'Cadastre 1997 to RGM04 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4475',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4470',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1880',
            'name' => 'Point 58 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4620',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19856',
            'name' => 'TM Reunion',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4626',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3727',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1926',
            'name' => 'Reunion 1947 to RGR92 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4626',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4627',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1912',
            'name' => 'RGR92 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4627',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1964',
            'name' => 'RGR92 to Reunion 1947 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4627',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4626',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5888',
            'name' => 'Combani 1950 to RGM04 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4632',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4470',
            'accuracy' => 0.3,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5521',
            'name' => 'Grand Comoros to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4646',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 999.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18011',
            'name' => 'Nord Algerie (ancienne)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4671',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30493',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18012',
            'name' => 'Sud Algerie (ancienne)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4671',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30494',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15870',
            'name' => 'Jouik 1961 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4679',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15709',
            'name' => 'Nouakchott 1965 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4680',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3981',
            'name' => 'Katanga Gauss zone A',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3986',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3982',
            'name' => 'Katanga Gauss zone B',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3987',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3983',
            'name' => 'Katanga Gauss zone C',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3988',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3984',
            'name' => 'Katanga Gauss zone D',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3989',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4067',
            'name' => 'Katanga 1955 to RGRDC 2005 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4046',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4416',
            'name' => 'Katanga Lambert',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4695',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4415',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17422',
            'name' => 'Congo Transverse Mercator zone 22',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4696',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3316',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17424',
            'name' => 'Congo Transverse Mercator zone 24',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4696',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3317',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17412',
            'name' => 'Congo Transverse Mercator zone 12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3318',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17414',
            'name' => 'Congo Transverse Mercator zone 14',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3319',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17416',
            'name' => 'Congo Transverse Mercator zone 16',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3320',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17418',
            'name' => 'Congo Transverse Mercator zone 18',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3321',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17420',
            'name' => 'Congo Transverse Mercator zone 20',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3322',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17422',
            'name' => 'Congo Transverse Mercator zone 22',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3323',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17424',
            'name' => 'Congo Transverse Mercator zone 24',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3324',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17426',
            'name' => 'Congo Transverse Mercator zone 26',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3325',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17428',
            'name' => 'Congo Transverse Mercator zone 28',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3326',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17430',
            'name' => 'Congo Transverse Mercator zone 30',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4697',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3327',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15850',
            'name' => 'IGN 1962 Kerguelen to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4698',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19899',
            'name' => 'Mauritius Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4699',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3337',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15784',
            'name' => 'Le Pouce 1934 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4699',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17412',
            'name' => 'Congo Transverse Mercator zone 12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4701',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3339',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17414',
            'name' => 'Congo Transverse Mercator zone 14',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4701',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3340',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17416',
            'name' => 'Congo Transverse Mercator zone 16',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4701',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3341',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15787',
            'name' => 'IGCB 1955 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4701',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15860',
            'name' => 'Mauritania 1999 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4702',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15790',
            'name' => 'Mhast (offshore) to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4705',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18072',
            'name' => 'Egypt Red Belt',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4706',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3355',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15792',
            'name' => 'Egypt Gulf of Suez S-650 TL to WGS 72BE (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4706',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4324',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15846',
            'name' => 'Egypt Gulf of Suez S-650 TL to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4706',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7894',
            'name' => 'Astro DOS 71 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4710',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7875',
            'name' => 'St. Helena Local Grid 1971',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4710',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7877',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7895',
            'name' => 'Astro DOS 71 to SHGD2015 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4710',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7886',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15797',
            'name' => 'Ascension Island 1958 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4712',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6907',
            'name' => 'Ayabelle Lighthouse to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4713',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15816',
            'name' => 'Tristan 1968 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4734',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18319',
            'name' => 'Libya TM',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3177',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18310',
            'name' => 'Libya TM zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3190',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18311',
            'name' => 'Libya TM zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3191',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18312',
            'name' => 'Libya TM zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3192',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18313',
            'name' => 'Libya TM zone 8',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3193',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18314',
            'name' => 'Libya TM zone 9',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3194',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18315',
            'name' => 'Libya TM zone 10',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3195',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18316',
            'name' => 'Libya TM zone 11',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3196',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18317',
            'name' => 'Libya TM zone 12',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3197',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18318',
            'name' => 'Libya TM zone 13',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3198',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15908',
            'name' => 'LGD2006 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4754',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19861',
            'name' => 'Laborde Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4810',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29701',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19911',
            'name' => 'Laborde Grid approximation',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4810',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29702',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1265',
            'name' => 'Tananarive (Paris) to Tananarive (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4810',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4297',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1266',
            'name' => 'Voirol 1875 (Paris) to Voirol 1875 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4811',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4304',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1881',
            'name' => 'Carthage (Paris) to Carthage (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4816',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4223',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6912',
            'name' => 'Bioko to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::6883',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 42.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6926',
            'name' => 'South East Island 1943 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::6892',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6913',
            'name' => 'Gambia to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::6894',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 43.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9770',
            'name' => 'RGTAAF07 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7073',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7876',
            'name' => 'St. Helena Local Grid (Tritan)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7881',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7882',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7897',
            'name' => 'St. Helena Tritan to SHGD2015 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7881',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7886',
            'accuracy' => 0.05,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7892',
            'name' => 'SHGD2015 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7886',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9226',
            'name' => 'SHGD2015 to Astro DOS 71 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7886',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4710',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9280',
            'name' => 'ITRF2005 to SA LLD height (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7910',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9279',
            'accuracy' => 0.07000000000000001,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9643',
            'name' => 'ITRF2005 to ITRF2005 + SA LLD height (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::7910',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9543',
            'accuracy' => 0.07000000000000001,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8882',
            'name' => 'Camacupa 2015 to WGS 84 (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 3.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8827',
            'name' => 'Camacupa 2015 to RSAO13 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'accuracy' => 3.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8819',
            'name' => 'RSAO13 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::16612',
            'name' => 'TM 12 SE',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8699',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9159',
            'accuracy' => 0,
        ],
    ];

    public static function getSupportedTransformations(): array
    {
        return static::$sridData;
    }
}
