<?php

/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateOperation;

/**
 * @internal
 */
class CRSTransformationsSouthAmerica
{
    /**
     * @var array<array{operation: string, name: string, source_crs: string, target_crs: string, accuracy: float}>
     */
    protected static array $sridData = [
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10134',
            'name' => 'SIRGAS-Chile 2021 to ITRF2014 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20039',
            'target_crs' => 'urn:ogc:def:crs:EPSG::7789',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18065',
            'name' => 'Colombia MAGNA 2018 Far West zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::11114',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18066',
            'name' => 'Colombia MAGNA 2018 West zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::11115',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18067',
            'name' => 'Colombia MAGNA 2018 Bogota zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::11116',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18068',
            'name' => 'Colombia MAGNA 2018 East Central zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::11117',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18069',
            'name' => 'Colombia MAGNA 2018 East zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::11118',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10149',
            'name' => 'MAGNA-SIRGAS 2018 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9376',
            'name' => 'Colombia Transverse Mercator',
            'source_crs' => 'urn:ogc:def:crs:EPSG::20046',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9377',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19924',
            'name' => 'Tobago Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4157',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2066',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1555',
            'name' => 'Naparima 1955 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4158',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4160',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2081',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1528',
            'name' => 'Chos Malal 1914 to Campo Inchauspe (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4160',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9257',
            'name' => 'Chos Malal 1914 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4160',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9258',
            'name' => 'Chos Malal 1914 to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4160',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4161',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2082',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9259',
            'name' => 'Pampa del Castillo to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4161',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4161',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9284',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18033',
            'name' => 'Argentina zone 3',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4161',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9285',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1581',
            'name' => 'SIRGAS 1995 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4170',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1767',
            'name' => 'REGVEN to SIRGAS 1995 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4189',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4170',
            'accuracy' => 0.02,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1768',
            'name' => 'REGVEN to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4189',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22171',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22172',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18033',
            'name' => 'Argentina zone 3',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22173',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18034',
            'name' => 'Argentina zone 4',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22174',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18035',
            'name' => 'Argentina zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22175',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18036',
            'name' => 'Argentina zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22176',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18037',
            'name' => 'Argentina zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22177',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1774',
            'name' => 'POSGAR 98 to SIRGAS 1995 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4170',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1773',
            'name' => 'POSGAR 98 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4190',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5050',
            'name' => 'Aratu to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5052',
            'name' => 'Aratu to SIRGAS 2000 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5054',
            'name' => 'Aratu to SIRGAS 2000 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5056',
            'name' => 'Aratu to SIRGAS 2000 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5058',
            'name' => 'Aratu to SIRGAS 2000 (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5060',
            'name' => 'Aratu to SIRGAS 2000 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5062',
            'name' => 'Aratu to SIRGAS 2000 (7)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5064',
            'name' => 'Aratu to SIRGAS 2000 (8)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5066',
            'name' => 'Aratu to SIRGAS 2000 (9)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4208',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18051',
            'name' => 'Colombia West zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::21896',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18052',
            'name' => 'Colombia Bogota zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::21897',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18053',
            'name' => 'Colombia East Central zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::21898',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18054',
            'name' => 'Colombia East zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::21899',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15730',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (9)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15731',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (10)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15732',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15733',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (12)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15734',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (13)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15735',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (14)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15736',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (15)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15737',
            'name' => 'Bogota 1975 to MAGNA-SIRGAS (16)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22191',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22192',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18033',
            'name' => 'Argentina zone 3',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22193',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18034',
            'name' => 'Argentina zone 4',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22194',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18035',
            'name' => 'Argentina zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22195',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18036',
            'name' => 'Argentina zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22196',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18037',
            'name' => 'Argentina zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22197',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1527',
            'name' => 'Campo Inchauspe to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15782',
            'name' => 'Campo Inchauspe to POSGAR 94 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5350',
            'name' => 'Campo Inchauspe to POSGAR 2007 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4221',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4069',
            'name' => 'Chua to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4224',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1132',
            'name' => 'Corrego Alegre 1970-72 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4225',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 8.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6191',
            'name' => 'Corrego Alegre 1970-72 to SAD69 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4225',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5526',
            'name' => 'Corrego Alegre 1970-72 to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4225',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6193',
            'name' => 'Corrego Alegre 1970-72 to SIRGAS 2000 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4225',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1771',
            'name' => 'La Canoa to REGVEN (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4247',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4189',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8674',
            'name' => 'La Canoa to PSAD56 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4247',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1096',
            'name' => 'La Canoa to WGS 84 (13)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4247',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1516',
            'name' => 'La Canoa to WGS 84 (18)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4247',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10135',
            'name' => 'PSAD56 to SIRGAS-Chile 2021 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::20041',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10136',
            'name' => 'PSAD56 to SIRGAS-Chile 2021 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::20041',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10137',
            'name' => 'PSAD56 to SIRGAS-Chile 2021 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::20041',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19976',
            'name' => 'ICN Regional',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2317',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18161',
            'name' => 'Peru west zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::24891',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18162',
            'name' => 'Peru central zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::24892',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18163',
            'name' => 'Peru east zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::24893',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3971',
            'name' => 'PSAD56 to SIRGAS 1995 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4170',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1769',
            'name' => 'PSAD56 to REGVEN (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4189',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1095',
            'name' => 'PSAD56 to WGS 84 (13)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 15.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1201',
            'name' => 'PSAD56 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 42.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1202',
            'name' => 'PSAD56 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 19.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1205',
            'name' => 'PSAD56 to WGS 84 (5)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1206',
            'name' => 'PSAD56 to WGS 84 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 7.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1207',
            'name' => 'PSAD56 to WGS 84 (7)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1208',
            'name' => 'PSAD56 to WGS 84 (8)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 16.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1209',
            'name' => 'PSAD56 to WGS 84 (9)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 23.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1582',
            'name' => 'PSAD56 to WGS 84 (10)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 3.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1583',
            'name' => 'PSAD56 to WGS 84 (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1811',
            'name' => 'PSAD56 to WGS 84 (12)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::3990',
            'name' => 'PSAD56 to WGS 84 (14)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6971',
            'name' => 'PSAD56 to WGS 84 (15)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6972',
            'name' => 'PSAD56 to WGS 84 (16)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6973',
            'name' => 'PSAD56 to WGS 84 (17)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 17.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6949',
            'name' => 'PSAD56 to SIRGAS-Chile 2002 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6950',
            'name' => 'PSAD56 to SIRGAS-Chile 2002 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6951',
            'name' => 'PSAD56 to SIRGAS-Chile 2002 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9339',
            'name' => 'PSAD56 to SIRGAS-Chile 2010 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8949',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9340',
            'name' => 'PSAD56 to SIRGAS-Chile 2010 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8949',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9341',
            'name' => 'PSAD56 to SIRGAS-Chile 2010 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8949',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9342',
            'name' => 'PSAD56 to SIRGAS-Chile 2013 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9148',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9343',
            'name' => 'PSAD56 to SIRGAS-Chile 2013 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9148',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9344',
            'name' => 'PSAD56 to SIRGAS-Chile 2013 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9148',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9345',
            'name' => 'PSAD56 to SIRGAS-Chile 2016 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9153',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9346',
            'name' => 'PSAD56 to SIRGAS-Chile 2016 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9153',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9347',
            'name' => 'PSAD56 to SIRGAS-Chile 2016 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9153',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18260',
            'name' => 'Maracaibo Grid (M1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4249',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2101',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18261',
            'name' => 'Maracaibo Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4249',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2102',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18262',
            'name' => 'Maracaibo Grid (M3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4249',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2103',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18263',
            'name' => 'Maracaibo La Rosa Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4249',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2104',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4254',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2083',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1529',
            'name' => 'Hito XVIII to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4254',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1892',
            'name' => 'Hito XVIII 1963 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4254',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1307',
            'name' => 'Naparima 1972 to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4271',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1225',
            'name' => 'Sapper Hill 1943 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4292',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19975',
            'name' => 'Trinidad Grid (Clarke\'s foot)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4302',
            'target_crs' => 'urn:ogc:def:crs:EPSG::2314',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19925',
            'name' => 'Trinidad Grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4302',
            'target_crs' => 'urn:ogc:def:crs:EPSG::30200',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1296',
            'name' => 'Trinidad 1903 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4302',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5386',
            'name' => 'Yacare to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4309',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5385',
            'name' => 'Yacare to SIRGAS-ROU98 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4309',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5381',
            'accuracy' => 1.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::17054',
            'name' => 'TM 54 NW',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4311',
            'target_crs' => 'urn:ogc:def:crs:EPSG::31154',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19954',
            'name' => 'Suriname Old TM',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4311',
            'target_crs' => 'urn:ogc:def:crs:EPSG::31170',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19955',
            'name' => 'Suriname TM',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4311',
            'target_crs' => 'urn:ogc:def:crs:EPSG::31171',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1235',
            'name' => 'Zanderij to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4311',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 11.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6702',
            'name' => 'TM 60 SW',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6703',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8033',
            'name' => 'TM Zone 20N (US survey foot)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8035',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8034',
            'name' => 'TM Zone 21N (US survey foot)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8036',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::10138',
            'name' => 'SAD69 to SIRGAS-Chile 2021 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::20041',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19941',
            'name' => 'Brazil Polyconic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::29101',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1864',
            'name' => 'SAD69 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 19.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1865',
            'name' => 'SAD69 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 9.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1866',
            'name' => 'SAD69 to WGS 84 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1867',
            'name' => 'SAD69 to WGS 84 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 8.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1869',
            'name' => 'SAD69 to WGS 84 (6)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1870',
            'name' => 'SAD69 to WGS 84 (7)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 6.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1871',
            'name' => 'SAD69 to WGS 84 (8)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1872',
            'name' => 'SAD69 to WGS 84 (9)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 12.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1873',
            'name' => 'SAD69 to WGS 84 (10)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 26.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1874',
            'name' => 'SAD69 to WGS 84 (11)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 9.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1875',
            'name' => 'SAD69 to WGS 84 (12)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1876',
            'name' => 'SAD69 to WGS 84 (13)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 8.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1877',
            'name' => 'SAD69 to WGS 84 (14)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6974',
            'name' => 'SAD69 to WGS 84 (17)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 4.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6975',
            'name' => 'SAD69 to WGS 84 (18)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 4.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6976',
            'name' => 'SAD69 to WGS 84 (19)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 7.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6977',
            'name' => 'SAD69 to WGS 84 (20)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 6.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15485',
            'name' => 'SAD69 to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5528',
            'name' => 'SAD69 to SIRGAS 2000 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6968',
            'name' => 'SAD69 to SIRGAS-Chile 2002 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6970',
            'name' => 'SAD69 to SIRGAS-Chile 2002 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7448',
            'name' => 'SAD69 to SIRGAS-Chile 2002 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::7449',
            'name' => 'SAD69 to SIRGAS-Chile 2002 (3)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5360',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9348',
            'name' => 'SAD69 to SIRGAS-Chile 2010 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8949',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9349',
            'name' => 'SAD69 to SIRGAS-Chile 2013 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9148',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9350',
            'name' => 'SAD69 to SIRGAS-Chile 2016 (4)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4618',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9153',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1906',
            'name' => 'CSG67 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4623',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 10.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1908',
            'name' => 'CSG67 to RGFG95 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4623',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4624',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::4840',
            'name' => 'RGFG95 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4624',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15894',
            'name' => 'SIRGAS 2000 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5640',
            'name' => 'Petrobras Mercator',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5641',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19941',
            'name' => 'Brazil Polyconic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5880',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18055',
            'name' => 'Colombia MAGNA Far West zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3114',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18056',
            'name' => 'Colombia MAGNA West zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3115',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18057',
            'name' => 'Colombia MAGNA Bogota zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3116',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18058',
            'name' => 'Colombia MAGNA East Central zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3117',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18059',
            'name' => 'Colombia MAGNA East zone',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::3118',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15738',
            'name' => 'MAGNA-SIRGAS to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6212',
            'name' => 'Arauca urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6244',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6213',
            'name' => 'Armenia urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6245',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6214',
            'name' => 'Barranquilla urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6246',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6215',
            'name' => 'Bogota urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6247',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6216',
            'name' => 'Bucaramanga urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6248',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6217',
            'name' => 'Cali urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6249',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6218',
            'name' => 'Cartagena urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6250',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6219',
            'name' => 'Cucuta urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6251',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6220',
            'name' => 'Florencia urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6252',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6221',
            'name' => 'Ibague urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6253',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6222',
            'name' => 'Inirida urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6254',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6223',
            'name' => 'Leticia urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6255',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6224',
            'name' => 'Manizales urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6256',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6225',
            'name' => 'Medellin urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6257',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6226',
            'name' => 'Mitu urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6258',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6227',
            'name' => 'Mocoa urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6259',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6228',
            'name' => 'Monteria urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6260',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6229',
            'name' => 'Neiva urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6261',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6230',
            'name' => 'Pasto urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6262',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6231',
            'name' => 'Pereira urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6263',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6232',
            'name' => 'Popayan urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6264',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6233',
            'name' => 'Puerto Carreno urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6265',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6234',
            'name' => 'Quibdo urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6266',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6235',
            'name' => 'Riohacha urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6267',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6236',
            'name' => 'San Andres urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6268',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6237',
            'name' => 'San Jose del Guaviare urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6269',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6238',
            'name' => 'Santa Marta urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6270',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6239',
            'name' => 'Sucre urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6271',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6240',
            'name' => 'Tunja urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6272',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6241',
            'name' => 'Valledupar urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6273',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6242',
            'name' => 'Villavicencio urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6274',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::6243',
            'name' => 'Yopal urban grid',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4686',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6275',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22181',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22182',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18033',
            'name' => 'Argentina zone 3',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22183',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18034',
            'name' => 'Argentina zone 4',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22184',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18035',
            'name' => 'Argentina zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22185',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18036',
            'name' => 'Argentina zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22186',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18037',
            'name' => 'Argentina zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::22187',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1210',
            'name' => 'POSGAR 94 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4694',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::15806',
            'name' => 'Easter Island 1967 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4719',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 44.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::1755',
            'name' => 'Bogota 1975 (Bogota) to Bogota 1975 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4802',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4218',
            'accuracy' => 0.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9051',
            'name' => 'ITRF94 to SIRGAS 1995 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4916',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4974',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8952',
            'name' => 'ITRF97 to SIRGAS-CON DGF00P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4918',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8915',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9052',
            'name' => 'ITRF2000 to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4988',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8953',
            'name' => 'ITRF2000 to SIRGAS-CON DGF01P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8917',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8954',
            'name' => 'ITRF2000 to SIRGAS-CON DGF01P02 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8919',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8955',
            'name' => 'ITRF2000 to SIRGAS-CON DGF02P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8921',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8956',
            'name' => 'ITRF2000 to SIRGAS-CON DGF04P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8923',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8957',
            'name' => 'ITRF2000 to SIRGAS-CON DGF05P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8925',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8958',
            'name' => 'ITRF2000 to SIRGAS-CON DGF06P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8927',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8962',
            'name' => 'ITRF2008 to SIRGAS-CON SIR10P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5332',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8935',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8963',
            'name' => 'ITRF2008 to SIRGAS-CON SIR11P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5332',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8937',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9264',
            'name' => 'POSGAR 2007 to WGS 84 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5497',
            'name' => 'POSGAR 2007 to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5343',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5344',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18033',
            'name' => 'Argentina zone 3',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5345',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18034',
            'name' => 'Argentina zone 4',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5346',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18035',
            'name' => 'Argentina zone 5',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5347',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18036',
            'name' => 'Argentina zone 6',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5348',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18037',
            'name' => 'Argentina zone 7',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5349',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9497',
            'name' => 'Gauss-Kruger CABA 2019',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5340',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9498',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9256',
            'name' => 'POSGAR 2007 to SRVN16 height (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5342',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9255',
            'accuracy' => 0.05,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9621',
            'name' => 'POSGAR 2007 to POSGAR 2007 + SRVN16 height (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5342',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9521',
            'accuracy' => 0.05,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5374',
            'name' => 'MARGEN to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5354',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9177',
            'name' => 'SIRGAS-Chile 2002 to ITRF2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5358',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5378',
            'name' => 'Peru96 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5373',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5384',
            'name' => 'SIRGAS-ROU98 to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5381',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 1.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5525',
            'name' => 'Corrego Alegre 1961 to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5524',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 2.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5529',
            'name' => 'SAD69(96) to SIRGAS 2000 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5527',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 0.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::5881',
            'name' => 'SAD69(96) to SIRGAS 2000 (2)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5527',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4674',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::19941',
            'name' => 'Brazil Polyconic',
            'source_crs' => 'urn:ogc:def:crs:EPSG::5527',
            'target_crs' => 'urn:ogc:def:crs:EPSG::5530',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8967',
            'name' => 'IGS14 to SIRGAS-CON SIR17P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8227',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8945',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9178',
            'name' => 'SIRGAS-Chile 2010 to IGS08 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::8947',
            'target_crs' => 'urn:ogc:def:crs:EPSG::6934',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8959',
            'name' => 'IGS05 to SIRGAS-CON DGF07P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9010',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8929',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8960',
            'name' => 'IGS05 to SIRGAS-CON DGF08P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9010',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8931',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8961',
            'name' => 'IGS05 to SIRGAS-CON SIR09P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9010',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8933',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8964',
            'name' => 'IGb08 to SIRGAS-CON SIR13P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8939',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8965',
            'name' => 'IGb08 to SIRGAS-CON SIR14P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8941',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::8966',
            'name' => 'IGb08 to SIRGAS-CON SIR15P01 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'target_crs' => 'urn:ogc:def:crs:EPSG::8943',
            'accuracy' => 0.01,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9179',
            'name' => 'SIRGAS-Chile 2013 to IGb08 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9146',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9180',
            'name' => 'SIRGAS-Chile 2016 to IGb08 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9151',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'accuracy' => 0.1,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9260',
            'name' => 'Tapi Aike to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 5.0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18031',
            'name' => 'Argentina zone 1',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9249',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9248',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9250',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9261',
            'name' => 'MMN to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9251',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9251',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9252',
            'accuracy' => 0,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::9262',
            'name' => 'MMS to WGS 84 (1)',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9253',
            'target_crs' => 'urn:ogc:def:crs:EPSG::4326',
            'accuracy' => 2.5,
        ],
        [
            'operation' => 'urn:ogc:def:coordinateOperation:EPSG::18032',
            'name' => 'Argentina zone 2',
            'source_crs' => 'urn:ogc:def:crs:EPSG::9253',
            'target_crs' => 'urn:ogc:def:crs:EPSG::9254',
            'accuracy' => 0,
        ],
    ];

    /**
     * @return array<array{operation: string, name: string, source_crs: string, target_crs: string, accuracy: float}>
     */
    public static function getSupportedTransformations(): array
    {
        return static::$sridData;
    }
}
