checks:
  php: true

tools:
  external_code_coverage:
    runs: 9    # Scrutinizer will wait for this many code coverage submissions
    timeout: 3600    # Timeout in seconds.

filter:
  excluded_paths:
    - 'tests/'
    - 'src/CoordinateOperation/Params'
    - 'src/Geometry/Extents'
    - 'src/EPSG/Import/'

build:
  environment:
    # Languages
    php:
      version: "8.0"
      ini:
        memory_limit: "-1"

  dependencies:
    override:
      - COMPOSER_ROOT_VERSION=5.x-dev composer update

  tests:
    override:
      - php-scrutinizer-run
