<?php
/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateReferenceSystem;

use PHPCoord\Geometry\BoundingArea;

/**
 * @internal
 * This file contains the Geocentric CRS SRID data, it only exists here because otherwise the main file becomes too large
 * for PHPStorm to analyse with its default settings and therefore the constants in it aren't available for
 * code-completion which defeats the whole point of having them...
 */
trait GeocentricSRIDData
{
    /**
     * @var array<string, array{name: string, coordinate_system: string, datum: string, extent: BoundingArea|array<string>, extent_description: string, help: string}>
     */
    protected static array $sridData = [
        'urn:ogc:def:crs:EPSG::3822' => [
            'name' => 'TWD97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1026',
            'extent' => ['1228'],
            'extent_description' => 'Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::3887' => [
            'name' => 'IGRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1029',
            'extent' => ['1124'],
            'extent_description' => 'Iraq - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4000' => [
            'name' => 'MOLDREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1032',
            'extent' => ['1162'],
            'extent_description' => 'Moldova.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4039' => [
            'name' => 'RGRDC 2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1033',
            'extent' => ['3613'],
            'extent_description' => 'The Democratic Republic of the Congo (Zaire) - south of a line through Bandundu, Seke and Pweto - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4073' => [
            'name' => 'SREF98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1034',
            'extent' => ['4543'],
            'extent_description' => 'Serbia including Vojvodina.',
            'help' => 'Replaced by SRB_ETRS89 (STRS00) (CRS code 8683).',
        ],
        'urn:ogc:def:crs:EPSG::4079' => [
            'name' => 'REGCAN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1035',
            'extent' => ['3199'],
            'extent_description' => 'Spain - Canary Islands onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4465' => [
            'name' => 'RGSPM06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1038',
            'extent' => ['1220'],
            'extent_description' => 'St Pierre and Miquelon - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4468' => [
            'name' => 'RGM04',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1036',
            'extent' => ['1159'],
            'extent_description' => 'Mayotte - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4473' => [
            'name' => 'Cadastre 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1037',
            'extent' => ['3340'],
            'extent_description' => 'Mayotte - onshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4479' => [
            'name' => 'China Geodetic Coordinate System 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1043',
            'extent' => ['1067'],
            'extent_description' => 'China - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4481' => [
            'name' => 'Mexico ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1042',
            'extent' => ['1160'],
            'extent_description' => 'Mexico - onshore and offshore.',
            'help' => 'Replaced by Mexico ITRF2008 (CRS code 6363) from December 2010.',
        ],
        'urn:ogc:def:crs:EPSG::4556' => [
            'name' => 'RRAF 1991',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1047',
            'extent' => ['2824'],
            'extent_description' => 'French Antilles onshore and offshore - Guadeloupe (including Grande Terre, Basse Terre, Marie Galante, Les Saintes, Iles de la Petite Terre, La Desirade); Martinique; St Barthélemy; St Martin.',
            'help' => 'Replaces older local geographic 2D systems Fort Marigot and Sainte Anne CRS (codes 4621-22) in Guadeloupe and Fort Desaix (CRS code 4625) in Martinique. Replaced by RGAF09 (CRS code 5487).',
        ],
        'urn:ogc:def:crs:EPSG::4882' => [
            'name' => 'Slovenia 1996',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6765',
            'extent' => ['1212'],
            'extent_description' => 'Slovenia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4884' => [
            'name' => 'RSRGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6764',
            'extent' => ['3558'],
            'extent_description' => 'Antarctica - Ross Sea Region - nominally between 160°E and 150°W but includes buffer on eastern hemisphere margin to include Transantarctic Mountains',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4886' => [
            'name' => 'BDA2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6762',
            'extent' => ['1047'],
            'extent_description' => 'Bermuda - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4888' => [
            'name' => 'HTRS96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6761',
            'extent' => ['1076'],
            'extent_description' => 'Croatia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4890' => [
            'name' => 'WGS 66',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6760',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaced by WGS 72.',
        ],
        'urn:ogc:def:crs:EPSG::4892' => [
            'name' => 'NAD83(NSRS2007)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6759',
            'extent' => ['1511'],
            'extent_description' => 'Puerto Rico - onshore and offshore. United States (USA) onshore and offshore - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands - onshore and offshore.',
            'help' => 'Replaces NAD83(HARN) and NAD83(FBN). Replaced by NAD83(2011).',
        ],
        'urn:ogc:def:crs:EPSG::4894' => [
            'name' => 'JAD2001',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6758',
            'extent' => ['1128'],
            'extent_description' => 'Jamaica - onshore and offshore. Includes Morant Cays and Pedro Cays.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4896' => [
            'name' => 'ITRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6896',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF2000 (CRS code 4919). Replaced by ITRF2008 (CRS code 5332).',
        ],
        'urn:ogc:def:crs:EPSG::4897' => [
            'name' => 'DGN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6755',
            'extent' => ['1122'],
            'extent_description' => 'Indonesia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4899' => [
            'name' => 'LGD2006',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6754',
            'extent' => ['1143'],
            'extent_description' => 'Libya - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4906' => [
            'name' => 'RGNC91-93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6749',
            'extent' => ['1174'],
            'extent_description' => 'New Caledonia - onshore and offshore. Isle de Pins, Loyalty Islands, Huon Islands, Belep archipelago, Chesterfield Islands, and Walpole.',
            'help' => 'Replaces older local geographic 2D systems IGN56 Lifou, IGN72 Grande Terre, ST87 Ouvea, IGN53 Mare, ST84 Ile des Pins, ST71 Belep and NEA74 Noumea (CRS codes 4633, 4641-44, 4662 and 4750). Replaced by RGNC15 (CRS code 10308).',
        ],
        'urn:ogc:def:crs:EPSG::4908' => [
            'name' => 'GR96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6747',
            'extent' => ['1107'],
            'extent_description' => 'Greenland - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4910' => [
            'name' => 'ITRF88',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6647',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaced by ITRF89 (code 4911).',
        ],
        'urn:ogc:def:crs:EPSG::4911' => [
            'name' => 'ITRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6648',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF88 (code 4910). Replaced by ITRF90 (code 4912).',
        ],
        'urn:ogc:def:crs:EPSG::4912' => [
            'name' => 'ITRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6649',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF89 (code 4911). Replaced by ITRF91 (code 4913).',
        ],
        'urn:ogc:def:crs:EPSG::4913' => [
            'name' => 'ITRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6650',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF90 (code 4912). Replaced by ITRF92 (code 4914).',
        ],
        'urn:ogc:def:crs:EPSG::4914' => [
            'name' => 'ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6651',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF91 (code 4913). Replaced by ITRF93 (code 4915).',
        ],
        'urn:ogc:def:crs:EPSG::4915' => [
            'name' => 'ITRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6652',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF92 (code 4914). Replaced by ITRF94 (code 4916).',
        ],
        'urn:ogc:def:crs:EPSG::4916' => [
            'name' => 'ITRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6653',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF93 (code 4915). Replaced by ITRF96 (code 4917).',
        ],
        'urn:ogc:def:crs:EPSG::4917' => [
            'name' => 'ITRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6654',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF94 (code 4916). Replaced by ITRF97 (code 4918).',
        ],
        'urn:ogc:def:crs:EPSG::4918' => [
            'name' => 'ITRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6655',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF96 (code 4917). Replaced by ITRF2000 (code 4919).',
        ],
        'urn:ogc:def:crs:EPSG::4919' => [
            'name' => 'ITRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6656',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF97 (code 4918). Replaced by ITRF2005 (code 4896).',
        ],
        'urn:ogc:def:crs:EPSG::4920' => [
            'name' => 'GDM2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6742',
            'extent' => ['1151'],
            'extent_description' => 'Malaysia - onshore and offshore. Includes peninsular Malayasia, Sabah and Sarawak.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4922' => [
            'name' => 'PZ-90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6740',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaced by PZ-90.02 from 2007-09-20.',
        ],
        'urn:ogc:def:crs:EPSG::4924' => [
            'name' => 'Mauritania 1999',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6702',
            'extent' => ['1157'],
            'extent_description' => 'Mauritania - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4926' => [
            'name' => 'Korea 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6737',
            'extent' => ['1135'],
            'extent_description' => 'Republic of Korea (South Korea) - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4928' => [
            'name' => 'POSGAR 94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6694',
            'extent' => ['1033'],
            'extent_description' => 'Argentina - onshore and offshore.',
            'help' => 'Legally adopted in May 1997. Replaced by POSGAR 98 for scientific and many practical purposes until May 2009. Officially replaced by POSGAR 2007 in May 2009.',
        ],
        'urn:ogc:def:crs:EPSG::4930' => [
            'name' => 'Australian Antarctic',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6176',
            'extent' => ['1278'],
            'extent_description' => 'Antarctica between 45°E and 136°E and between 142°E and 160°E - Australian sector.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4932' => [
            'name' => 'CHTRS95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6151',
            'extent' => ['1286'],
            'extent_description' => 'Liechtenstein; Switzerland.',
            'help' => 'Referenced to ETRS89 at epoch 1993.0. For CRS used for topographic and cadastral purposes see CH1903+ (CRS code 4150).',
        ],
        'urn:ogc:def:crs:EPSG::4934' => [
            'name' => 'EST97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6180',
            'extent' => ['1090'],
            'extent_description' => 'Estonia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4936' => [
            'name' => 'ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6258',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Has been realized through ETRF89, ETRF90, ETRF91, ETRF92, ETRF93, ETRF94, ETRF96, ETRF97, ETRF2000, ETRF2005 and ETRF2014. This \'ensemble\' covers any or all of these realizations without distinction.',
        ],
        'urn:ogc:def:crs:EPSG::4938' => [
            'name' => 'GDA94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6283',
            'extent' => ['4177'],
            'extent_description' => 'Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4940' => [
            'name' => 'Hartebeesthoek94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6148',
            'extent' => ['4540'],
            'extent_description' => 'Eswatini (Swaziland); Lesotho; South Africa - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4942' => [
            'name' => 'IRENET95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6173',
            'extent' => ['1305'],
            'extent_description' => 'Ireland - onshore. United Kingdom (UK) - Northern Ireland (Ulster) - onshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4944' => [
            'name' => 'ISN93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6659',
            'extent' => ['1120'],
            'extent_description' => 'Iceland - onshore and offshore.',
            'help' => 'Replaced by ISN2004 (CRS code 5322).',
        ],
        'urn:ogc:def:crs:EPSG::4946' => [
            'name' => 'JGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6612',
            'extent' => ['1129'],
            'extent_description' => 'Japan - onshore and offshore.',
            'help' => 'From 21st October 2011 replaced by JGD2011 (CRS code 6666).',
        ],
        'urn:ogc:def:crs:EPSG::4948' => [
            'name' => 'LKS-92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6661',
            'extent' => ['1139'],
            'extent_description' => 'Latvia - onshore and offshore.',
            'help' => 'Replaced by LKS-2020 (CRS code 10303).',
        ],
        'urn:ogc:def:crs:EPSG::4950' => [
            'name' => 'LKS94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6126',
            'extent' => ['1145'],
            'extent_description' => 'Lithuania - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4952' => [
            'name' => 'Moznet',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6130',
            'extent' => ['1167'],
            'extent_description' => 'Mozambique - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4954' => [
            'name' => 'NAD83(CSRS)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6140',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Includes all versions of NAD83(CSRS) from v2 [CSRS98] onwards without specific identification. As such it has an accuracy of approximately 1m.',
        ],
        'urn:ogc:def:crs:EPSG::4956' => [
            'name' => 'NAD83(HARN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6152',
            'extent' => ['1337'],
            'extent_description' => 'American Samoa - onshore - Tutuila, Aunu\'u, Ofu, Olesega, Ta\'u and Rose islands. Guam - onshore. Northern Mariana Islands - onshore. Puerto Rico - onshore. United States (USA) - onshore Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin and Wyoming; offshore Gulf of Mexico continental shelf (GoM OCS). US Virgin Islands - onshore.',
            'help' => 'In CONUS and Hawaii replaces NAD83 for applications with an accuracy of better than 1m. Replaced by NAD83(FBN) in CONUS, American Samoa and Guam/NMI, by NAD83(NSRS2007) in Alaska, by NAD83(PA11) in Hawaii and by NAD83(HARN Corrected) in PRVI.',
        ],
        'urn:ogc:def:crs:EPSG::4958' => [
            'name' => 'NZGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6167',
            'extent' => ['1175'],
            'extent_description' => 'New Zealand - onshore and offshore. Includes Antipodes Islands, Auckland Islands, Bounty Islands, Chatham Islands, Cambell Island, Kermadec Islands, Raoul Island and Snares Islands.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4960' => [
            'name' => 'POSGAR 98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6190',
            'extent' => ['1033'],
            'extent_description' => 'Argentina - onshore and offshore.',
            'help' => 'Densification in Argentina of SIRGAS 1995. Until May 2009 replaced POSGAR 94 for many practical purposes (but not as the legal system). POSGAR 94 was officially replaced by POSGAR 2007 in May 2009.',
        ],
        'urn:ogc:def:crs:EPSG::4962' => [
            'name' => 'REGVEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6189',
            'extent' => ['1251'],
            'extent_description' => 'Venezuela - onshore and offshore.',
            'help' => 'Densification in Venezuela of SIRGAS.',
        ],
        'urn:ogc:def:crs:EPSG::4964' => [
            'name' => 'RGF93 v1',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6171',
            'extent' => ['1096'],
            'extent_description' => 'France - onshore and offshore, mainland and Corsica (France métropolitaine including Corsica).',
            'help' => 'Replaced by RGF93 v2 (CRS code 9775) from 2010-06-18.',
        ],
        'urn:ogc:def:crs:EPSG::4966' => [
            'name' => 'RGFG95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6624',
            'extent' => ['1097'],
            'extent_description' => 'French Guiana - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4970' => [
            'name' => 'RGR92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6627',
            'extent' => ['3902'],
            'extent_description' => 'Reunion - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4974' => [
            'name' => 'SIRGAS 1995',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6170',
            'extent' => ['3448'],
            'extent_description' => 'South America - onshore and offshore. Ecuador (mainland and Galapagos) - onshore and offshore.',
            'help' => 'Replaced by SIRGAS 2000 (CRS code 4988).',
        ],
        'urn:ogc:def:crs:EPSG::4976' => [
            'name' => 'SWEREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6619',
            'extent' => ['1225'],
            'extent_description' => 'Sweden - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4978' => [
            'name' => 'WGS 84',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6326',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4980' => [
            'name' => 'Yemen NGN96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6163',
            'extent' => ['1257'],
            'extent_description' => 'Yemen - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4982' => [
            'name' => 'IGM95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6670',
            'extent' => ['3343'],
            'extent_description' => 'Italy - onshore and offshore; San Marino, Vatican City State.',
            'help' => 'Replaced by RDN2008 (CRS code 6704) from 2011-11-10.',
        ],
        'urn:ogc:def:crs:EPSG::4984' => [
            'name' => 'WGS 72',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6322',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaced by WGS 84.',
        ],
        'urn:ogc:def:crs:EPSG::4986' => [
            'name' => 'WGS 72BE',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6324',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Broadcast ephemeris. Replaced by WGS 84.',
        ],
        'urn:ogc:def:crs:EPSG::4988' => [
            'name' => 'SIRGAS 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6674',
            'extent' => ['3418'],
            'extent_description' => 'Latin America - Central America and South America - onshore and offshore. Brazil - onshore and offshore.',
            'help' => 'Replaces SIRGAS 1995 system (CRS code 4974) for South America; expands SIRGAS to Central America.',
        ],
        'urn:ogc:def:crs:EPSG::4990' => [
            'name' => 'Lao 1993',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6677',
            'extent' => ['1138'],
            'extent_description' => 'Laos.',
            'help' => 'Replaced by Lao 1997. Lao 1993 coordinate values are within 1m of Lao 1997 values.',
        ],
        'urn:ogc:def:crs:EPSG::4992' => [
            'name' => 'Lao 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6678',
            'extent' => ['1138'],
            'extent_description' => 'Laos.',
            'help' => 'Replaces Lao 1993. Lao 1993 coordinate values are within 1m of Lao 1997 values.',
        ],
        'urn:ogc:def:crs:EPSG::4994' => [
            'name' => 'PRS92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6683',
            'extent' => ['1190'],
            'extent_description' => 'Philippines - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::4996' => [
            'name' => 'MAGNA-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6686',
            'extent' => ['1070'],
            'extent_description' => 'Colombia - onshore and offshore. Includes San Andres y Providencia, Malpelo Islands, Roncador Bank, Serrana Bank and Serranilla Bank.',
            'help' => 'For high accuracy purposes replaced by MAGNA-SIRGAS 2018 (code 20044).',
        ],
        'urn:ogc:def:crs:EPSG::4998' => [
            'name' => 'RGPF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6687',
            'extent' => ['1098'],
            'extent_description' => 'French Polynesia - onshore and offshore. Includes Society archipelago, Tuamotu archipelago, Marquesas Islands, Gambier Islands and Austral Islands.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5011' => [
            'name' => 'PTRA08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1041',
            'extent' => ['3670'],
            'extent_description' => 'Portugal - Azores and Madeira island groups and surrounding EEZ - Flores, Corvo; Graciosa, Terceira, Sao Jorge, Pico, Faial; Sao Miguel, Santa Maria; Madeira, Porto Santo, Desertas; Selvagens.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5244' => [
            'name' => 'GDBD2009',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1056',
            'extent' => ['1055'],
            'extent_description' => 'Brunei Darussalam - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5250' => [
            'name' => 'TUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1057',
            'extent' => ['1237'],
            'extent_description' => 'Türkiye (Turkey) - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5262' => [
            'name' => 'DRUKREF 03',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1058',
            'extent' => ['1048'],
            'extent_description' => 'Bhutan.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5322' => [
            'name' => 'ISN2004',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1060',
            'extent' => ['1120'],
            'extent_description' => 'Iceland - onshore and offshore.',
            'help' => 'Replaces ISN93 (CRS code 4944). Replaced by ISN2016 (CRS code 8084).',
        ],
        'urn:ogc:def:crs:EPSG::5332' => [
            'name' => 'ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1061',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF2005 (CRS code 4896). Replaced by ITRF2014 (CRS code 7789).',
        ],
        'urn:ogc:def:crs:EPSG::5341' => [
            'name' => 'POSGAR 2007',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1062',
            'extent' => ['1033'],
            'extent_description' => 'Argentina - onshore and offshore.',
            'help' => 'Adopted as official replacement of POSGAR 94 in May 2009. Also replaces de facto use of POSGAR 98 as of same date.',
        ],
        'urn:ogc:def:crs:EPSG::5352' => [
            'name' => 'MARGEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1063',
            'extent' => ['1049'],
            'extent_description' => 'Bolivia.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5358' => [
            'name' => 'SIRGAS-Chile 2002',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1064',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => 'Densification of SIRGAS 2000 within Chile. Replaced by SIRGAS-Chile 2010 (CRS code 8947).',
        ],
        'urn:ogc:def:crs:EPSG::5363' => [
            'name' => 'CR05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1065',
            'extent' => ['1074'],
            'extent_description' => 'Costa Rica - onshore and offshore.',
            'help' => 'Replaced by CR-SIRGAS (CRS code 8905) from April 2018.',
        ],
        'urn:ogc:def:crs:EPSG::5368' => [
            'name' => 'MACARIO SOLIS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1066',
            'extent' => ['1186'],
            'extent_description' => 'Panama - onshore and offshore.',
            'help' => 'Densification of SIRGAS 2000 within Panama.',
        ],
        'urn:ogc:def:crs:EPSG::5369' => [
            'name' => 'Peru96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1067',
            'extent' => ['1189'],
            'extent_description' => 'Peru - onshore and offshore.',
            'help' => 'Densification of SIRGAS95 in Peru.',
        ],
        'urn:ogc:def:crs:EPSG::5379' => [
            'name' => 'SIRGAS-ROU98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1068',
            'extent' => ['1247'],
            'extent_description' => 'Uruguay - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5391' => [
            'name' => 'SIRGAS_ES2007.8',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1069',
            'extent' => ['1087'],
            'extent_description' => 'El Salvador - onshore and offshore.',
            'help' => 'Densification of SIRGAS 2000 within El Salvador.',
        ],
        'urn:ogc:def:crs:EPSG::5487' => [
            'name' => 'RGAF09',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1073',
            'extent' => ['2824'],
            'extent_description' => 'French Antilles onshore and offshore - Guadeloupe (including Grande Terre, Basse Terre, Marie Galante, Les Saintes, Iles de la Petite Terre, La Desirade); Martinique; St Barthélemy; St Martin.',
            'help' => 'Replaces RRAF 1991 (CRS code 4556).',
        ],
        'urn:ogc:def:crs:EPSG::5544' => [
            'name' => 'PNG94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1076',
            'extent' => ['1187'],
            'extent_description' => 'Papua New Guinea - onshore and offshore. Includes Bismark archipelago, Louisade archipelago, Admiralty Islands, d\'Entrecasteaux Islands, northern Solomon Islands, Trobriand Islands, New Britain, New Ireland, Woodlark, and associated islands.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::5558' => [
            'name' => 'UCS-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1077',
            'extent' => ['1242'],
            'extent_description' => 'Ukraine - onshore and offshore.',
            'help' => 'Adopted 1st January 2007. Defined through transformation code 7817 at epoch 2005.0.',
        ],
        'urn:ogc:def:crs:EPSG::5591' => [
            'name' => 'FEH2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1078',
            'extent' => ['3889'],
            'extent_description' => 'Fehmarnbelt area of Denmark and Germany.',
            'help' => 'Trans-national system created due to small (but unacceptable for engineering tolerance) differences between the German and Danish realisations of ETRS89.',
        ],
        'urn:ogc:def:crs:EPSG::5828' => [
            'name' => 'DB_REF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1081',
            'extent' => ['3339'],
            'extent_description' => 'Germany - onshore - states of Baden-Wurtemberg, Bayern, Berlin, Brandenburg, Bremen, Hamburg, Hessen, Mecklenburg-Vorpommern, Niedersachsen, Nordrhein-Westfalen, Rheinland-Pfalz, Saarland, Sachsen, Sachsen-Anhalt, Schleswig-Holstein, Thuringen.',
            'help' => 'Geometric component of both DB_REF2003 and DB_REF2016 systems. Derived from ETRS89 through transformation code 5826.',
        ],
        'urn:ogc:def:crs:EPSG::5884' => [
            'name' => 'TGD2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1095',
            'extent' => ['1234'],
            'extent_description' => 'Tonga - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::6133' => [
            'name' => 'CIGD11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1100',
            'extent' => ['1063'],
            'extent_description' => 'Cayman Islands - onshore and offshore. Includes Grand Cayman, Little Cayman and Cayman Brac.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::6309' => [
            'name' => 'CGRS93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1112',
            'extent' => ['3236'],
            'extent_description' => 'Cyprus - onshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::6317' => [
            'name' => 'NAD83(2011)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1116',
            'extent' => ['1511'],
            'extent_description' => 'Puerto Rico - onshore and offshore. United States (USA) onshore and offshore - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands - onshore and offshore.',
            'help' => 'Replaces NAD83(CORS96) and NAD83(NSRS2007) (CRS codes 6781 and 4892).',
        ],
        'urn:ogc:def:crs:EPSG::6320' => [
            'name' => 'NAD83(PA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1117',
            'extent' => ['4162'],
            'extent_description' => 'American Samoa, Marshall Islands, United States (USA) - Hawaii, United States minor outlying islands; onshore and offshore.',
            'help' => 'Replaces NAD83(HARN) and NAD83(FBN) in Hawaii and American Samoa.',
        ],
        'urn:ogc:def:crs:EPSG::6323' => [
            'name' => 'NAD83(MA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1118',
            'extent' => ['4167'],
            'extent_description' => 'Guam, Northern Mariana Islands and Palau; onshore and offshore.',
            'help' => 'Replaces NAD83(HARN) (GGN93) and NAD83(FBN) in Guam.',
        ],
        'urn:ogc:def:crs:EPSG::6363' => [
            'name' => 'Mexico ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1120',
            'extent' => ['1160'],
            'extent_description' => 'Mexico - onshore and offshore.',
            'help' => 'Replaces Mexico ITRF92 (CRS code 4481) from December 2010.',
        ],
        'urn:ogc:def:crs:EPSG::6666' => [
            'name' => 'JGD2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1128',
            'extent' => ['1129'],
            'extent_description' => 'Japan - onshore and offshore.',
            'help' => 'Replaces JGD2000 (CRS code 4946) with effect from 21st October 2011.',
        ],
        'urn:ogc:def:crs:EPSG::6704' => [
            'name' => 'RDN2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1132',
            'extent' => ['3343'],
            'extent_description' => 'Italy - onshore and offshore; San Marino, Vatican City State.',
            'help' => 'Replaces IGM95 (CRS code 4982) from 2011-11-10.',
        ],
        'urn:ogc:def:crs:EPSG::6781' => [
            'name' => 'NAD83(CORS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1133',
            'extent' => ['1511'],
            'extent_description' => 'Puerto Rico - onshore and offshore. United States (USA) onshore and offshore - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands - onshore and offshore.',
            'help' => 'Replaced by NAD83(2011) (CRS code 6317) from 2011-09-06.',
        ],
        'urn:ogc:def:crs:EPSG::6934' => [
            'name' => 'IGS08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1141',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Used for products from International GNSS Service (IGS) analysis centres from 2011-04-17 through 2012-10-06. Replaces IGS05 (code 9010). Replaced by IGb08 (code 9015). For most practical purposes IGS08 is equivalent to ITRF2008.',
        ],
        'urn:ogc:def:crs:EPSG::6981' => [
            'name' => 'IG05 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1142',
            'extent' => ['2603'],
            'extent_description' => 'Israel - onshore; Palestine Territory - onshore.',
            'help' => 'Intermediate system not used for spatial referencing - use IGD05 (CRS code 6978).',
        ],
        'urn:ogc:def:crs:EPSG::6988' => [
            'name' => 'IG05/12 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1144',
            'extent' => ['2603'],
            'extent_description' => 'Israel - onshore; Palestine Territory - onshore.',
            'help' => 'Intermediate system not used for spatial referencing - use IGD05/12 (CRS code 6985).',
        ],
        'urn:ogc:def:crs:EPSG::7071' => [
            'name' => 'RGTAAF07',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1113',
            'extent' => ['4246'],
            'extent_description' => 'French Southern Territories - onshore and offshore: Amsterdam and St Paul, Crozet, Europa and Kerguelen. Antarctica - Adelie Land coastal area.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::7134' => [
            'name' => 'IGD05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1114',
            'extent' => ['1126'],
            'extent_description' => 'Israel - onshore and offshore.',
            'help' => 'Replaced by IGD05/12 (CRS code 7137).',
        ],
        'urn:ogc:def:crs:EPSG::7137' => [
            'name' => 'IGD05/12',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1115',
            'extent' => ['1126'],
            'extent_description' => 'Israel - onshore and offshore.',
            'help' => 'Replaces IGD05 (CRS code 7134).',
        ],
        'urn:ogc:def:crs:EPSG::7371' => [
            'name' => 'ONGD14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1147',
            'extent' => ['1183'],
            'extent_description' => 'Oman - onshore and offshore.',
            'help' => 'In Oman replaces usage of WGS 84 (G873) from 2014. Replaced by ONGD17 (CRS code 9292) from March 2019.',
        ],
        'urn:ogc:def:crs:EPSG::7656' => [
            'name' => 'WGS 84 (G730)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1152',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (Transit) (CRS code 7815) from 1994-06-29. Replaced by WGS84 (G873) (CRS code 7658) from 1997-01-29.',
        ],
        'urn:ogc:def:crs:EPSG::7658' => [
            'name' => 'WGS 84 (G873)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1153',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (G730) (CRS code 7656) from 1997-01-29. Replaced by WGS 84 (G1150) (CRS code 7660) from 2002-01-20.',
        ],
        'urn:ogc:def:crs:EPSG::7660' => [
            'name' => 'WGS 84 (G1150)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1154',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (G873) (CRS code 7658) from 2002-01-20. Replaced by WGS 84 (G1674) (CRS code 7662) from 2012-02-08.',
        ],
        'urn:ogc:def:crs:EPSG::7662' => [
            'name' => 'WGS 84 (G1674)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1155',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (G1150) (CRS code 7660) from 2012-02-08. Replaced by WGS 84 (G1762) (CRS code 7664) from 2013-10-16.',
        ],
        'urn:ogc:def:crs:EPSG::7664' => [
            'name' => 'WGS 84 (G1762)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1156',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (G1674) (CRS code 7662) from 2013-10-16. Redesignated WGS 84 (G1762\') in 2015 after changes to 7 NGA tracking station locations and antennas. Replaced by WGS 84 (G2139) (CRS code 9753) from 2021-01-03.',
        ],
        'urn:ogc:def:crs:EPSG::7677' => [
            'name' => 'PZ-90.02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1157',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces PZ-90 (CRS code 4922) from 2007-09-20. Replaced by PZ-90.11 (CRS code 7679) from 2014-01-15.',
        ],
        'urn:ogc:def:crs:EPSG::7679' => [
            'name' => 'PZ-90.11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1158',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces PZ-90.02 (CRS code 7677) from 2014-01-15.',
        ],
        'urn:ogc:def:crs:EPSG::7681' => [
            'name' => 'GSK-2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1159',
            'extent' => ['1198'],
            'extent_description' => 'Russian Federation - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::7684' => [
            'name' => 'Kyrg-06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1160',
            'extent' => ['1137'],
            'extent_description' => 'Kyrgyzstan.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::7789' => [
            'name' => 'ITRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1165',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF2008 (CRS code 5332). Replaced by ITRF2020 (CRS code 9988).',
        ],
        'urn:ogc:def:crs:EPSG::7796' => [
            'name' => 'BGS2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1167',
            'extent' => ['1056'],
            'extent_description' => 'Bulgaria - onshore and offshore.',
            'help' => 'Adopted 2010-07-29.',
        ],
        'urn:ogc:def:crs:EPSG::7815' => [
            'name' => 'WGS 84 (Transit)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1166',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaced by WGS84 (G730) (CRS code 7656) from 1994-06-29.',
        ],
        'urn:ogc:def:crs:EPSG::7842' => [
            'name' => 'GDA2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1168',
            'extent' => ['4177'],
            'extent_description' => 'Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::7879' => [
            'name' => 'St. Helena Tritan',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1173',
            'extent' => ['3183'],
            'extent_description' => 'St Helena, Ascension and Tristan da Cunha - St Helena Island - onshore.',
            'help' => 'Replaced by SHGD2015 (CRS code 7884) from 2015.',
        ],
        'urn:ogc:def:crs:EPSG::7884' => [
            'name' => 'SHGD2015',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1174',
            'extent' => ['3183'],
            'extent_description' => 'St Helena, Ascension and Tristan da Cunha - St Helena Island - onshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::7914' => [
            'name' => 'ETRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1178',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaced by ETRF90 (code 7916).',
        ],
        'urn:ogc:def:crs:EPSG::7916' => [
            'name' => 'ETRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1179',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF89 (code 7914). Replaced by ETRF91 (code 7918).',
        ],
        'urn:ogc:def:crs:EPSG::7918' => [
            'name' => 'ETRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1180',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF90 (code 7916). Replaced by ETRF92 (code 7920).',
        ],
        'urn:ogc:def:crs:EPSG::7920' => [
            'name' => 'ETRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1181',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF91 (code 7918). Replaced by ETRF93 (code 7922).',
        ],
        'urn:ogc:def:crs:EPSG::7922' => [
            'name' => 'ETRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1182',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF92 (code 7920). Replaced by ETRF94 (code 7924).',
        ],
        'urn:ogc:def:crs:EPSG::7924' => [
            'name' => 'ETRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1183',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF93 (code 7922). Replaced by ETRF96 (code 7926).',
        ],
        'urn:ogc:def:crs:EPSG::7926' => [
            'name' => 'ETRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1184',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF94 (code 7924). Replaced by ETRF97 (code 7928).',
        ],
        'urn:ogc:def:crs:EPSG::7928' => [
            'name' => 'ETRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1185',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF96 (code 7926). Replaced by ETRF2000 (code 7930).',
        ],
        'urn:ogc:def:crs:EPSG::7930' => [
            'name' => 'ETRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1186',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF97 (code 7928). On the publication of ETRF2005 (code 8397), the EUREF Technical Working Group recommended that ETRF2000 be the realization of ETRS89. ETRF2014 (code 8401) is technically superior to all earlier realizations of ETRS89.',
        ],
        'urn:ogc:def:crs:EPSG::8084' => [
            'name' => 'ISN2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1187',
            'extent' => ['1120'],
            'extent_description' => 'Iceland - onshore and offshore.',
            'help' => 'Replaces ISN2004 (CRS code 5322) from September 2017.',
        ],
        'urn:ogc:def:crs:EPSG::8227' => [
            'name' => 'IGS14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1191',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Used for products from the International GNSS Service (IGS) from 2017-01-29 to 2020-05-16. Replaces IGb08 (code 9015), replaced by IGb14 (code 9378). For most practical purposes IGS14 is equivalent to ITRF2014.',
        ],
        'urn:ogc:def:crs:EPSG::8230' => [
            'name' => 'NAD83(CSRS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1192',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 1996-01-01. Replaced by NAD83(CSRS)v2 (CRS code 8233).',
        ],
        'urn:ogc:def:crs:EPSG::8233' => [
            'name' => 'NAD83(CSRS)v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1193',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 1998-01-01 and by the provincial governments of British Columbia, New Brunswick, Prince Edward Island and Quebec. Replaces NAD83(CSRS96). Replaced by NAD83(CSRS)v3 (CRS code 8238).',
        ],
        'urn:ogc:def:crs:EPSG::8238' => [
            'name' => 'NAD83(CSRS)v3',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1194',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 1999-01-01 and by the provincial governments of Alberta, British Columbia, Manitoba, Newfoundland and Labrador, Nova Scotia, Ontario and Saskatchewan. Replaces NAD83(CSRS)v2. Replaced by NAD83(CSRS)v4.',
        ],
        'urn:ogc:def:crs:EPSG::8242' => [
            'name' => 'NAD83(CSRS)v4',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1195',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 2002-01-01 and by the provincial governments of Alberta and British Columbia. Replaces NAD83(CSRS)v3. Replaced by NAD83(CSRS)v5 (CRS code 8247).',
        ],
        'urn:ogc:def:crs:EPSG::8247' => [
            'name' => 'NAD83(CSRS)v5',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1196',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 2006-01-01. Replaces NAD83(CSRS)v4. Replaced by NAD83(CSRS)v6 (CRS code 8250).',
        ],
        'urn:ogc:def:crs:EPSG::8250' => [
            'name' => 'NAD83(CSRS)v6',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1197',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 2010-01-01 and the provincial governments of Alberta, British Columbia, Manitoba, Newfoundland and Labrador, Nova Scotia, Ontario and Prince Edward Island. Replaces NAD83(CSRS)v5. Replaced by NAD83(CSRS)v7.',
        ],
        'urn:ogc:def:crs:EPSG::8253' => [
            'name' => 'NAD83(CSRS)v7',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1198',
            'extent' => ['1061'],
            'extent_description' => 'Canada - onshore and offshore - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon.',
            'help' => 'Adopted by the Canadian federal government from 2017-05-01 and the provincial government of Alberta. Replaces NAD83(CSRS)v6.',
        ],
        'urn:ogc:def:crs:EPSG::8397' => [
            'name' => 'ETRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1204',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'On publication in 2007 of this CRS, the EUREF Technical Working Group recommended that ETRF2000 (EPSG code 7930) remained as the preferred realization of ETRS89. Replaced by ETRF2014 (code 8401).',
        ],
        'urn:ogc:def:crs:EPSG::8401' => [
            'name' => 'ETRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1206',
            'extent' => ['1298'],
            'extent_description' => 'Europe - onshore and offshore: Albania; Andorra; Austria; Belgium; Bosnia and Herzegovina; Bulgaria; Croatia; Cyprus; Czechia; Denmark; Estonia; Faroe Islands; Finland; France; Germany; Gibraltar; Greece; Hungary; Ireland; Italy; Kosovo; Latvia; Liechtenstein; Lithuania; Luxembourg; Malta; Moldova; Monaco; Montenegro; Netherlands; North Macedonia; Norway including Svalbard and Jan Mayen; Poland; Portugal; Romania; San Marino; Serbia; Slovakia; Slovenia; Spain; Sweden; Switzerland; United Kingdom (UK) including Channel Islands and Isle of Man; Vatican City State.',
            'help' => 'Replaces ETRF2005 (code 8397). ETRF2014 is technically superior to ETRF2000 but ETRF2000 and other previous realizations may be preferred for backward compatibility reasons. Differences between ETRF2014 and ETRF2000 can reach 7cm.',
        ],
        'urn:ogc:def:crs:EPSG::8425' => [
            'name' => 'Hong Kong Geodetic CS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1209',
            'extent' => ['1118'],
            'extent_description' => 'China - Hong Kong - onshore and offshore.',
            'help' => 'Locally sometimes referred to as ITRF96 or WGS 84, these are not strictly correct.',
        ],
        'urn:ogc:def:crs:EPSG::8429' => [
            'name' => 'Macao 2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1208',
            'extent' => ['1147'],
            'extent_description' => 'China - Macao - onshore and offshore.',
            'help' => 'Locally sometimes referred to as ITRF2005, this is not strictly correct.',
        ],
        'urn:ogc:def:crs:EPSG::8541' => [
            'name' => 'NAD83(FBN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1211',
            'extent' => ['4515'],
            'extent_description' => 'American Samoa - Tutuila, Aunu\'u, Ofu, Olesega, Ta\'u and Rose islands - onshore. Guam - onshore. Northern Mariana Islands - onshore. Puerto Rico - onshore. United States (USA) - CONUS - Alabama; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming - onshore plus Gulf of Mexico offshore continental shelf (GoM OCS). US Virgin Islands - onshore.',
            'help' => 'In Continental US, American Samoa, Guam/NMI and PRVI, replaces NAD83(HARN). In Continental US, Puerto Rico and US Virgin Islands replaced by NAD83(NSRS2007). In American Samoa and Hawaii replaced by NAD83(PA11). In Guam/NMI replaced by NAD83(MA11).',
        ],
        'urn:ogc:def:crs:EPSG::8543' => [
            'name' => 'NAD83(HARN Corrected)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1212',
            'extent' => ['3634'],
            'extent_description' => 'Puerto Rico and US Virgin Islands - onshore.',
            'help' => 'In PRVI replaces NAD83(HARN) = NAD83(1993 PRVI) to correct errors. Replaced by NAD83(FBN) = NAD83(2002 PRVI).',
        ],
        'urn:ogc:def:crs:EPSG::8683' => [
            'name' => 'SRB_ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1214',
            'extent' => ['4543'],
            'extent_description' => 'Serbia including Vojvodina.',
            'help' => 'Replaces SREF98 (CRS code 4073).',
        ],
        'urn:ogc:def:crs:EPSG::8697' => [
            'name' => 'RSAO13',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1220',
            'extent' => ['1029'],
            'extent_description' => 'Angola - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::8816' => [
            'name' => 'MTRF-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1218',
            'extent' => ['1206'],
            'extent_description' => 'Saudi Arabia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::8898' => [
            'name' => 'RGWF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1223',
            'extent' => ['1255'],
            'extent_description' => 'Wallis and Futuna - onshore and offshore - Uvea, Futuna, and Alofi.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::8905' => [
            'name' => 'CR-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1225',
            'extent' => ['1074'],
            'extent_description' => 'Costa Rica - onshore and offshore.',
            'help' => 'Replaces CR05 (CRS code 5363) from April 2018.',
        ],
        'urn:ogc:def:crs:EPSG::8915' => [
            'name' => 'SIRGAS-CON DGF00P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1227',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaced by SIRGAS-CON DGF01P01 (CRS code 8917).',
        ],
        'urn:ogc:def:crs:EPSG::8917' => [
            'name' => 'SIRGAS-CON DGF01P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1228',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF00P01 (CRS code 8915). Replaced by SIRGAS-CON DGF01P02 (CRS code 8919).',
        ],
        'urn:ogc:def:crs:EPSG::8919' => [
            'name' => 'SIRGAS-CON DGF01P02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1229',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF01P01 (CRS code 8917). Replaced by SIRGAS-CON DGF02P01 (CRS code 8921).',
        ],
        'urn:ogc:def:crs:EPSG::8921' => [
            'name' => 'SIRGAS-CON DGF02P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1230',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF01P02 (CRS code 8919). Replaced by SIRGAS-CON DGF04P01 (CRS code 8923).',
        ],
        'urn:ogc:def:crs:EPSG::8923' => [
            'name' => 'SIRGAS-CON DGF04P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1231',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF02P01 (CRS code 8921). Replaced by SIRGAS-CON DGF05P01 (CRS code 8925).',
        ],
        'urn:ogc:def:crs:EPSG::8925' => [
            'name' => 'SIRGAS-CON DGF05P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1232',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF04P01 (CRS code 8923). Replaced by SIRGAS-CON DGF06P01 (CRS code 8927).',
        ],
        'urn:ogc:def:crs:EPSG::8927' => [
            'name' => 'SIRGAS-CON DGF06P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1233',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF05P01 (CRS code 8925). Replaced by SIRGAS-CON DGF07P01 (CRS code 8929).',
        ],
        'urn:ogc:def:crs:EPSG::8929' => [
            'name' => 'SIRGAS-CON DGF07P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1234',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF06P01 (CRS code 8927). Replaced by SIRGAS-CON DGF08P01 (CRS code 8931).',
        ],
        'urn:ogc:def:crs:EPSG::8931' => [
            'name' => 'SIRGAS-CON DGF08P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1235',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF07P01 (CRS code 8929). Replaced by SIRGAS-CON SIR09P01 (CRS code 8933).',
        ],
        'urn:ogc:def:crs:EPSG::8933' => [
            'name' => 'SIRGAS-CON SIR09P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1236',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON DGF08P01 (CRS code 8931). Replaced by SIRGAS-CON SIR10P01 (CRS code 8935).',
        ],
        'urn:ogc:def:crs:EPSG::8935' => [
            'name' => 'SIRGAS-CON SIR10P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1237',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR09P01 (CRS code 8933). Replaced by SIRGAS-CON SIR11P01 (CRS code 8937).',
        ],
        'urn:ogc:def:crs:EPSG::8937' => [
            'name' => 'SIRGAS-CON SIR11P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1238',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR10P01 (CRS code 8935). Replaced by SIRGAS-CON SIR13P01 (CRS code 8939).',
        ],
        'urn:ogc:def:crs:EPSG::8939' => [
            'name' => 'SIRGAS-CON SIR13P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1239',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR11P01 (CRS code 8937). Replaced by SIRGAS-CON SIR14P01 (CRS code 8941).',
        ],
        'urn:ogc:def:crs:EPSG::8941' => [
            'name' => 'SIRGAS-CON SIR14P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1240',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR13P01 (CRS code 8939). Replaced by SIRGAS-CON SIR15P01 (CRS code 8943).',
        ],
        'urn:ogc:def:crs:EPSG::8943' => [
            'name' => 'SIRGAS-CON SIR15P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1241',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR14P01 (CRS code 8941). Replaced by SIRGAS-CON SIR17P01 (CRS code 8945).',
        ],
        'urn:ogc:def:crs:EPSG::8945' => [
            'name' => 'SIRGAS-CON SIR17P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1242',
            'extent' => ['4530'],
            'extent_description' => 'Latin America - Central America and South America, onshore and offshore.',
            'help' => 'Replaces SIRGAS-CON SIR15P01 (CRS code 8943).',
        ],
        'urn:ogc:def:crs:EPSG::8947' => [
            'name' => 'SIRGAS-Chile 2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1243',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => 'Densification of SIRGAS-CON within Chile at epoch 2010.00. Replaces SIRGAS-Chile 2002 (CRS code 5358), replaced by SIRGAS-Chile 2013 (CRS code 9146) due to significant tectonic deformation.',
        ],
        'urn:ogc:def:crs:EPSG::9001' => [
            'name' => 'IGS97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1244',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Adopted by the International GNSS Service (IGS) from 2000-06-04 through 2001-12-01. Replaced by IGS00 (CRS code 9004). For all practical purposes IGS97 is equivalent to ITRF97.',
        ],
        'urn:ogc:def:crs:EPSG::9004' => [
            'name' => 'IGS00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1245',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Adopted by the International GNSS Service (IGS) from 2001-12-02 through 2004-01-10. Replaces IGS97, replaced by IGb00 (CRS codes 9001 and 9007). For all practical purposes IGS00 is equivalent to ITRF2000.',
        ],
        'urn:ogc:def:crs:EPSG::9007' => [
            'name' => 'IGb00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1246',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Adopted by the International GNSS Service (IGS) from 2004-01-11 through 2006-11-04. Replaces IGS00, replaced by IGS05 (CRS codes 9004 and 9010). For all practical purposes IGb00 is equivalent to ITRF2000.',
        ],
        'urn:ogc:def:crs:EPSG::9010' => [
            'name' => 'IGS05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1247',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Adopted by the International GNSS Service (IGS) from 2006-11-05 through 2011-04-16. Replaces IGb00, replaced by IGS08 (CRS codes 9007 and 6834). For all practical purposes IGS05 is equivalent to ITRF2005.',
        ],
        'urn:ogc:def:crs:EPSG::9015' => [
            'name' => 'IGb08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1248',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Adopted by the International GNSS Service (IGS) from 2012-10-07 through 2017-01-28. Replaces IGS08, replaced by IGS14 (CRS codes 6934 and 8227). For all practical purposes IGb08 is equivalent to ITRF2008.',
        ],
        'urn:ogc:def:crs:EPSG::9070' => [
            'name' => 'NAD83(MARP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1221',
            'extent' => ['4167'],
            'extent_description' => 'Guam, Northern Mariana Islands and Palau; onshore and offshore.',
            'help' => 'Replaces NAD83(HARN) (GGN93) and NAD83(FBN) in Guam. Replaced by NAD83(MA11).',
        ],
        'urn:ogc:def:crs:EPSG::9073' => [
            'name' => 'NAD83(PACP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1249',
            'extent' => ['4162'],
            'extent_description' => 'American Samoa, Marshall Islands, United States (USA) - Hawaii, United States minor outlying islands; onshore and offshore.',
            'help' => 'Replaces NAD83(HARN) and NAD83(FBN) in Hawaii and American Samoa. Replaced by NAD83(PA11).',
        ],
        'urn:ogc:def:crs:EPSG::9138' => [
            'name' => 'KOSOVAREF01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1251',
            'extent' => ['4542'],
            'extent_description' => 'Kosovo.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9146' => [
            'name' => 'SIRGAS-Chile 2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1252',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => 'Densification of SIRGAS-CON within Chile at epoch 2013.00. Replaces SIRGAS-Chile 2010 (CRS code 8947), replaced by SIRGAS-Chile 2016 (CRS code 9151) due to significant tectonic deformation.',
        ],
        'urn:ogc:def:crs:EPSG::9151' => [
            'name' => 'SIRGAS-Chile 2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1253',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => 'Densification of SIRGAS-CON within Chile at epoch 2016.00. Replaces SIRGAS-Chile 2013 (CRS code 9146), replaced by SIRGAS-Chile 2021 (CRS code 20039) due to significant tectonic deformation.',
        ],
        'urn:ogc:def:crs:EPSG::9266' => [
            'name' => 'MGI',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6312',
            'extent' => ['1037'],
            'extent_description' => 'Austria.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9292' => [
            'name' => 'ONGD17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1263',
            'extent' => ['1183'],
            'extent_description' => 'Oman - onshore and offshore.',
            'help' => 'Replaces ONGD14 (CRS code 7371) from March 2019.',
        ],
        'urn:ogc:def:crs:EPSG::9307' => [
            'name' => 'ATRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1291',
            'extent' => ['4177'],
            'extent_description' => 'Australia including Lord Howe Island, Macquarie Island, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9331' => [
            'name' => 'KSA-GRF17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1268',
            'extent' => ['1206'],
            'extent_description' => 'Saudi Arabia - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9378' => [
            'name' => 'IGb14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1272',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Used for products from the International GNSS Service (IGS) from 2020-05-17. Replaces IGS14 (code 8227), replaced by IGS20 (code 10176). For most practical purposes IGb14 is equivalent to ITRF2014.',
        ],
        'urn:ogc:def:crs:EPSG::9468' => [
            'name' => 'SRGI2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1293',
            'extent' => ['1122'],
            'extent_description' => 'Indonesia - onshore and offshore.',
            'help' => 'Supports horizontal component of national horizontal control network (JKHN). Adopted 2013-10-11. Replaces DGN95 and all older systems.',
        ],
        'urn:ogc:def:crs:EPSG::9545' => [
            'name' => 'LTF2004(G)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1295',
            'extent' => ['4613'],
            'extent_description' => 'France and Italy - on or related to the rail route from Lyon to Turin.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9694' => [
            'name' => 'REDGEOMIN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1304',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9700' => [
            'name' => 'ETRF2000-PL',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1305',
            'extent' => ['1192'],
            'extent_description' => 'Poland - onshore and offshore.',
            'help' => 'Adopted from 2012-12-01.',
        ],
        'urn:ogc:def:crs:EPSG::9753' => [
            'name' => 'WGS 84 (G2139)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1309',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces WGS 84 (G1762) (CRS code 7664) from 2021-01-03.',
        ],
        'urn:ogc:def:crs:EPSG::9775' => [
            'name' => 'RGF93 v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1312',
            'extent' => ['1096'],
            'extent_description' => 'France - onshore and offshore, mainland and Corsica (France métropolitaine including Corsica).',
            'help' => 'Replaces RGF93 v1 (CRS code 4964) from 2010-06-18. Replaced by RGF93 v2b (CRS code 9780) from 2021-01-05.',
        ],
        'urn:ogc:def:crs:EPSG::9780' => [
            'name' => 'RGF93 v2b',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1313',
            'extent' => ['1096'],
            'extent_description' => 'France - onshore and offshore, mainland and Corsica (France métropolitaine including Corsica).',
            'help' => 'Replaces RGF93 v2 (CRS code 9775) from 2021-01-05.',
        ],
        'urn:ogc:def:crs:EPSG::9892' => [
            'name' => 'LUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6181',
            'extent' => ['1146'],
            'extent_description' => 'Luxembourg.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::9988' => [
            'name' => 'ITRF2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1322',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Replaces ITRF2014 (CRS code 7789).',
        ],
        'urn:ogc:def:crs:EPSG::10176' => [
            'name' => 'IGS20',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1333',
            'extent' => ['1262'],
            'extent_description' => 'World.',
            'help' => 'Used for products from the International GNSS Service (IGS) from 2022-11-27. Replaces IGb14 (code 9378). For most practical purposes IGS20 is equivalent to ITRF2020.',
        ],
        'urn:ogc:def:crs:EPSG::10282' => [
            'name' => 'ETRS89/DREF91/2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1353',
            'extent' => ['1103'],
            'extent_description' => 'Germany - onshore and offshore.',
            'help' => 'German national realization of ETRS89. Replaces ETRS89/DREF91 Realization 2002 from 2016-12-01.',
        ],
        'urn:ogc:def:crs:EPSG::10297' => [
            'name' => 'RGSH2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1355',
            'extent' => ['1026'],
            'extent_description' => 'Algeria - onshore and offshore.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::10303' => [
            'name' => 'LKS-2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1356',
            'extent' => ['1139'],
            'extent_description' => 'Latvia - onshore and offshore.',
            'help' => 'Replaces LKS-92 (CRS code 4948).',
        ],
        'urn:ogc:def:crs:EPSG::10308' => [
            'name' => 'RGNC15',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1357',
            'extent' => ['1174'],
            'extent_description' => 'New Caledonia - onshore and offshore. Isle de Pins, Loyalty Islands, Huon Islands, Belep archipelago, Chesterfield Islands, and Walpole.',
            'help' => 'Replaces RGNC91-93 (CRS code 4906).',
        ],
        'urn:ogc:def:crs:EPSG::10326' => [
            'name' => 'BH_ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1358',
            'extent' => ['1050'],
            'extent_description' => 'Bosnia and Herzegovina.',
            'help' => '',
        ],
        'urn:ogc:def:crs:EPSG::20039' => [
            'name' => 'SIRGAS-Chile 2021',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1327',
            'extent' => ['1066'],
            'extent_description' => 'Chile - onshore and offshore. Includes Easter Island, Juan Fernandez Islands, San Felix, and Sala y Gomez.',
            'help' => 'Densification of SIRGAS-CON within Chile at epoch 2021.00. Replaces SIRGAS-Chile 2016 (CRS code 9151) due to significant tectonic deformation.',
        ],
        'urn:ogc:def:crs:EPSG::20044' => [
            'name' => 'MAGNA-SIRGAS 2018',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1329',
            'extent' => ['1070'],
            'extent_description' => 'Colombia - onshore and offshore. Includes San Andres y Providencia, Malpelo Islands, Roncador Bank, Serrana Bank and Serranilla Bank.',
            'help' => '',
        ],
    ];
}
