<?php
/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateReferenceSystem;

/**
 * @internal
 * This file contains the Geocentric CRS SRID data, it only exists here because otherwise the main file becomes too large
 * for PHPStorm to analyse with its default settings and therefore the constants in it aren't available for
 * code-completion which defeats the whole point of having them...
 */
trait GeocentricSRIDData
{
    protected static array $sridData = [
        'urn:ogc:def:crs:EPSG::3822' => [
            'name' => 'TWD97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1026',
            'extent' => ['1228'],
        ],
        'urn:ogc:def:crs:EPSG::3887' => [
            'name' => 'IGRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1029',
            'extent' => ['1124'],
        ],
        'urn:ogc:def:crs:EPSG::4000' => [
            'name' => 'MOLDREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1032',
            'extent' => ['1162'],
        ],
        'urn:ogc:def:crs:EPSG::4039' => [
            'name' => 'RGRDC 2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1033',
            'extent' => ['3613'],
        ],
        'urn:ogc:def:crs:EPSG::4073' => [
            'name' => 'SREF98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1034',
            'extent' => ['4543'],
        ],
        'urn:ogc:def:crs:EPSG::4079' => [
            'name' => 'REGCAN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1035',
            'extent' => ['3199'],
        ],
        'urn:ogc:def:crs:EPSG::4465' => [
            'name' => 'RGSPM06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1038',
            'extent' => ['1220'],
        ],
        'urn:ogc:def:crs:EPSG::4468' => [
            'name' => 'RGM04',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1036',
            'extent' => ['1159'],
        ],
        'urn:ogc:def:crs:EPSG::4473' => [
            'name' => 'Cadastre 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1037',
            'extent' => ['3340'],
        ],
        'urn:ogc:def:crs:EPSG::4479' => [
            'name' => 'China Geodetic Coordinate System 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1043',
            'extent' => ['1067'],
        ],
        'urn:ogc:def:crs:EPSG::4481' => [
            'name' => 'Mexico ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1042',
            'extent' => ['1160'],
        ],
        'urn:ogc:def:crs:EPSG::4556' => [
            'name' => 'RRAF 1991',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1047',
            'extent' => ['2824'],
        ],
        'urn:ogc:def:crs:EPSG::4882' => [
            'name' => 'Slovenia 1996',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6765',
            'extent' => ['1212'],
        ],
        'urn:ogc:def:crs:EPSG::4884' => [
            'name' => 'RSRGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6764',
            'extent' => ['3558'],
        ],
        'urn:ogc:def:crs:EPSG::4886' => [
            'name' => 'BDA2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6762',
            'extent' => ['1047'],
        ],
        'urn:ogc:def:crs:EPSG::4888' => [
            'name' => 'HTRS96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6761',
            'extent' => ['1076'],
        ],
        'urn:ogc:def:crs:EPSG::4890' => [
            'name' => 'WGS 66',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6760',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4892' => [
            'name' => 'NAD83(NSRS2007)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6759',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::4894' => [
            'name' => 'JAD2001',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6758',
            'extent' => ['1128'],
        ],
        'urn:ogc:def:crs:EPSG::4896' => [
            'name' => 'ITRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6896',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4897' => [
            'name' => 'DGN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6755',
            'extent' => ['1122'],
        ],
        'urn:ogc:def:crs:EPSG::4899' => [
            'name' => 'LGD2006',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6754',
            'extent' => ['1143'],
        ],
        'urn:ogc:def:crs:EPSG::4906' => [
            'name' => 'RGNC91-93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6749',
            'extent' => ['1174'],
        ],
        'urn:ogc:def:crs:EPSG::4908' => [
            'name' => 'GR96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6747',
            'extent' => ['1107'],
        ],
        'urn:ogc:def:crs:EPSG::4910' => [
            'name' => 'ITRF88',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6647',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4911' => [
            'name' => 'ITRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6648',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4912' => [
            'name' => 'ITRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6649',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4913' => [
            'name' => 'ITRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6650',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4914' => [
            'name' => 'ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6651',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4915' => [
            'name' => 'ITRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6652',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4916' => [
            'name' => 'ITRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6653',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4917' => [
            'name' => 'ITRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6654',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4918' => [
            'name' => 'ITRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6655',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4919' => [
            'name' => 'ITRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6656',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4920' => [
            'name' => 'GDM2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6742',
            'extent' => ['1151'],
        ],
        'urn:ogc:def:crs:EPSG::4922' => [
            'name' => 'PZ-90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6740',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4924' => [
            'name' => 'Mauritania 1999',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6702',
            'extent' => ['1157'],
        ],
        'urn:ogc:def:crs:EPSG::4926' => [
            'name' => 'Korea 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6737',
            'extent' => ['1135'],
        ],
        'urn:ogc:def:crs:EPSG::4928' => [
            'name' => 'POSGAR 94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6694',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::4930' => [
            'name' => 'Australian Antarctic',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6176',
            'extent' => ['1278'],
        ],
        'urn:ogc:def:crs:EPSG::4932' => [
            'name' => 'CHTRS95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6151',
            'extent' => ['1286'],
        ],
        'urn:ogc:def:crs:EPSG::4934' => [
            'name' => 'EST97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6180',
            'extent' => ['1090'],
        ],
        'urn:ogc:def:crs:EPSG::4936' => [
            'name' => 'ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6258',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::4938' => [
            'name' => 'GDA94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6283',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::4940' => [
            'name' => 'Hartebeesthoek94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6148',
            'extent' => ['4540'],
        ],
        'urn:ogc:def:crs:EPSG::4942' => [
            'name' => 'IRENET95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6173',
            'extent' => ['1305'],
        ],
        'urn:ogc:def:crs:EPSG::4944' => [
            'name' => 'ISN93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6659',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::4946' => [
            'name' => 'JGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6612',
            'extent' => ['1129'],
        ],
        'urn:ogc:def:crs:EPSG::4948' => [
            'name' => 'LKS92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6661',
            'extent' => ['1139'],
        ],
        'urn:ogc:def:crs:EPSG::4950' => [
            'name' => 'LKS94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6126',
            'extent' => ['1145'],
        ],
        'urn:ogc:def:crs:EPSG::4952' => [
            'name' => 'Moznet',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6130',
            'extent' => ['1167'],
        ],
        'urn:ogc:def:crs:EPSG::4954' => [
            'name' => 'NAD83(CSRS)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6140',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::4956' => [
            'name' => 'NAD83(HARN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6152',
            'extent' => ['1337'],
        ],
        'urn:ogc:def:crs:EPSG::4958' => [
            'name' => 'NZGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6167',
            'extent' => ['1175'],
        ],
        'urn:ogc:def:crs:EPSG::4960' => [
            'name' => 'POSGAR 98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6190',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::4962' => [
            'name' => 'REGVEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6189',
            'extent' => ['1251'],
        ],
        'urn:ogc:def:crs:EPSG::4964' => [
            'name' => 'RGF93 v1',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6171',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::4966' => [
            'name' => 'RGFG95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6624',
            'extent' => ['1097'],
        ],
        'urn:ogc:def:crs:EPSG::4970' => [
            'name' => 'RGR92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6627',
            'extent' => ['3902'],
        ],
        'urn:ogc:def:crs:EPSG::4974' => [
            'name' => 'SIRGAS 1995',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6170',
            'extent' => ['3448'],
        ],
        'urn:ogc:def:crs:EPSG::4976' => [
            'name' => 'SWEREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6619',
            'extent' => ['1225'],
        ],
        'urn:ogc:def:crs:EPSG::4978' => [
            'name' => 'WGS 84',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6326',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4980' => [
            'name' => 'Yemen NGN96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6163',
            'extent' => ['1257'],
        ],
        'urn:ogc:def:crs:EPSG::4982' => [
            'name' => 'IGM95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6670',
            'extent' => ['3343'],
        ],
        'urn:ogc:def:crs:EPSG::4984' => [
            'name' => 'WGS 72',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6322',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4986' => [
            'name' => 'WGS 72BE',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6324',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4988' => [
            'name' => 'SIRGAS 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6674',
            'extent' => ['3418'],
        ],
        'urn:ogc:def:crs:EPSG::4990' => [
            'name' => 'Lao 1993',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6677',
            'extent' => ['1138'],
        ],
        'urn:ogc:def:crs:EPSG::4992' => [
            'name' => 'Lao 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6678',
            'extent' => ['1138'],
        ],
        'urn:ogc:def:crs:EPSG::4994' => [
            'name' => 'PRS92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6683',
            'extent' => ['1190'],
        ],
        'urn:ogc:def:crs:EPSG::4996' => [
            'name' => 'MAGNA-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6686',
            'extent' => ['1070'],
        ],
        'urn:ogc:def:crs:EPSG::4998' => [
            'name' => 'RGPF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6687',
            'extent' => ['1098'],
        ],
        'urn:ogc:def:crs:EPSG::5011' => [
            'name' => 'PTRA08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1041',
            'extent' => ['3670'],
        ],
        'urn:ogc:def:crs:EPSG::5244' => [
            'name' => 'GDBD2009',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1056',
            'extent' => ['1055'],
        ],
        'urn:ogc:def:crs:EPSG::5250' => [
            'name' => 'TUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1057',
            'extent' => ['1237'],
        ],
        'urn:ogc:def:crs:EPSG::5262' => [
            'name' => 'DRUKREF 03',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1058',
            'extent' => ['1048'],
        ],
        'urn:ogc:def:crs:EPSG::5322' => [
            'name' => 'ISN2004',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1060',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::5332' => [
            'name' => 'ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1061',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::5341' => [
            'name' => 'POSGAR 2007',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1062',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::5352' => [
            'name' => 'MARGEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1063',
            'extent' => ['1049'],
        ],
        'urn:ogc:def:crs:EPSG::5358' => [
            'name' => 'SIRGAS-Chile 2002',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1064',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::5363' => [
            'name' => 'CR05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1065',
            'extent' => ['1074'],
        ],
        'urn:ogc:def:crs:EPSG::5368' => [
            'name' => 'MACARIO SOLIS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1066',
            'extent' => ['1186'],
        ],
        'urn:ogc:def:crs:EPSG::5369' => [
            'name' => 'Peru96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1067',
            'extent' => ['1189'],
        ],
        'urn:ogc:def:crs:EPSG::5379' => [
            'name' => 'SIRGAS-ROU98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1068',
            'extent' => ['1247'],
        ],
        'urn:ogc:def:crs:EPSG::5391' => [
            'name' => 'SIRGAS_ES2007.8',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1069',
            'extent' => ['1087'],
        ],
        'urn:ogc:def:crs:EPSG::5487' => [
            'name' => 'RGAF09',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1073',
            'extent' => ['2824'],
        ],
        'urn:ogc:def:crs:EPSG::5544' => [
            'name' => 'PNG94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1076',
            'extent' => ['1187'],
        ],
        'urn:ogc:def:crs:EPSG::5558' => [
            'name' => 'UCS-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1077',
            'extent' => ['1242'],
        ],
        'urn:ogc:def:crs:EPSG::5591' => [
            'name' => 'FEH2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1078',
            'extent' => ['3889'],
        ],
        'urn:ogc:def:crs:EPSG::5828' => [
            'name' => 'DB_REF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1081',
            'extent' => ['3339'],
        ],
        'urn:ogc:def:crs:EPSG::5884' => [
            'name' => 'TGD2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1095',
            'extent' => ['1234'],
        ],
        'urn:ogc:def:crs:EPSG::6133' => [
            'name' => 'CIGD11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1100',
            'extent' => ['1063'],
        ],
        'urn:ogc:def:crs:EPSG::6309' => [
            'name' => 'CGRS93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1112',
            'extent' => ['3236'],
        ],
        'urn:ogc:def:crs:EPSG::6317' => [
            'name' => 'NAD83(2011)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1116',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::6320' => [
            'name' => 'NAD83(PA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1117',
            'extent' => ['4162'],
        ],
        'urn:ogc:def:crs:EPSG::6323' => [
            'name' => 'NAD83(MA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1118',
            'extent' => ['4167'],
        ],
        'urn:ogc:def:crs:EPSG::6363' => [
            'name' => 'Mexico ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1120',
            'extent' => ['1160'],
        ],
        'urn:ogc:def:crs:EPSG::6666' => [
            'name' => 'JGD2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1128',
            'extent' => ['1129'],
        ],
        'urn:ogc:def:crs:EPSG::6704' => [
            'name' => 'RDN2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1132',
            'extent' => ['3343'],
        ],
        'urn:ogc:def:crs:EPSG::6781' => [
            'name' => 'NAD83(CORS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1133',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::6934' => [
            'name' => 'IGS08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1141',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::6981' => [
            'name' => 'IG05 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1142',
            'extent' => ['2603'],
        ],
        'urn:ogc:def:crs:EPSG::6988' => [
            'name' => 'IG05/12 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1144',
            'extent' => ['2603'],
        ],
        'urn:ogc:def:crs:EPSG::7071' => [
            'name' => 'RGTAAF07',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1113',
            'extent' => ['4246'],
        ],
        'urn:ogc:def:crs:EPSG::7134' => [
            'name' => 'IGD05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1114',
            'extent' => ['1126'],
        ],
        'urn:ogc:def:crs:EPSG::7137' => [
            'name' => 'IGD05/12',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1115',
            'extent' => ['1126'],
        ],
        'urn:ogc:def:crs:EPSG::7371' => [
            'name' => 'ONGD14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1147',
            'extent' => ['1183'],
        ],
        'urn:ogc:def:crs:EPSG::7656' => [
            'name' => 'WGS 84 (G730)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1152',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7658' => [
            'name' => 'WGS 84 (G873)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1153',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7660' => [
            'name' => 'WGS 84 (G1150)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1154',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7662' => [
            'name' => 'WGS 84 (G1674)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1155',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7664' => [
            'name' => 'WGS 84 (G1762)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1156',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7677' => [
            'name' => 'PZ-90.02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1157',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7679' => [
            'name' => 'PZ-90.11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1158',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7681' => [
            'name' => 'GSK-2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1159',
            'extent' => ['1198'],
        ],
        'urn:ogc:def:crs:EPSG::7684' => [
            'name' => 'Kyrg-06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1160',
            'extent' => ['1137'],
        ],
        'urn:ogc:def:crs:EPSG::7789' => [
            'name' => 'ITRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1165',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7796' => [
            'name' => 'BGS2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1167',
            'extent' => ['1056'],
        ],
        'urn:ogc:def:crs:EPSG::7815' => [
            'name' => 'WGS 84 (Transit)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1166',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7842' => [
            'name' => 'GDA2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1168',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::7879' => [
            'name' => 'St. Helena Tritan',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1173',
            'extent' => ['3183'],
        ],
        'urn:ogc:def:crs:EPSG::7884' => [
            'name' => 'SHGD2015',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1174',
            'extent' => ['3183'],
        ],
        'urn:ogc:def:crs:EPSG::7914' => [
            'name' => 'ETRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1178',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7916' => [
            'name' => 'ETRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1179',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7918' => [
            'name' => 'ETRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1180',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7920' => [
            'name' => 'ETRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1181',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7922' => [
            'name' => 'ETRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1182',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7924' => [
            'name' => 'ETRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1183',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7926' => [
            'name' => 'ETRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1184',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7928' => [
            'name' => 'ETRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1185',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7930' => [
            'name' => 'ETRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1186',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8084' => [
            'name' => 'ISN2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1187',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::8227' => [
            'name' => 'IGS14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1191',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::8230' => [
            'name' => 'NAD83(CSRS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1192',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8233' => [
            'name' => 'NAD83(CSRS)v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1193',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8238' => [
            'name' => 'NAD83(CSRS)v3',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1194',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8242' => [
            'name' => 'NAD83(CSRS)v4',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1195',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8247' => [
            'name' => 'NAD83(CSRS)v5',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1196',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8250' => [
            'name' => 'NAD83(CSRS)v6',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1197',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8253' => [
            'name' => 'NAD83(CSRS)v7',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1198',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8397' => [
            'name' => 'ETRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1204',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8401' => [
            'name' => 'ETRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1206',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8425' => [
            'name' => 'Hong Kong Geodetic CS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1209',
            'extent' => ['1118'],
        ],
        'urn:ogc:def:crs:EPSG::8429' => [
            'name' => 'Macao 2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1208',
            'extent' => ['1147'],
        ],
        'urn:ogc:def:crs:EPSG::8541' => [
            'name' => 'NAD83(FBN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1211',
            'extent' => ['4515'],
        ],
        'urn:ogc:def:crs:EPSG::8543' => [
            'name' => 'NAD83(HARN Corrected)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1212',
            'extent' => ['3634'],
        ],
        'urn:ogc:def:crs:EPSG::8683' => [
            'name' => 'SRB_ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1214',
            'extent' => ['4543'],
        ],
        'urn:ogc:def:crs:EPSG::8697' => [
            'name' => 'RSAO13',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1220',
            'extent' => ['1029'],
        ],
        'urn:ogc:def:crs:EPSG::8816' => [
            'name' => 'MTRF-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1218',
            'extent' => ['1206'],
        ],
        'urn:ogc:def:crs:EPSG::8898' => [
            'name' => 'RGWF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1223',
            'extent' => ['1255'],
        ],
        'urn:ogc:def:crs:EPSG::8905' => [
            'name' => 'CR-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1225',
            'extent' => ['1074'],
        ],
        'urn:ogc:def:crs:EPSG::8915' => [
            'name' => 'SIRGAS-CON DGF00P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1227',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8917' => [
            'name' => 'SIRGAS-CON DGF01P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1228',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8919' => [
            'name' => 'SIRGAS-CON DGF01P02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1229',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8921' => [
            'name' => 'SIRGAS-CON DGF02P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1230',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8923' => [
            'name' => 'SIRGAS-CON DGF04P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1231',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8925' => [
            'name' => 'SIRGAS-CON DGF05P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1232',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8927' => [
            'name' => 'SIRGAS-CON DGF06P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1233',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8929' => [
            'name' => 'SIRGAS-CON DGF07P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1234',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8931' => [
            'name' => 'SIRGAS-CON DGF08P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1235',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8933' => [
            'name' => 'SIRGAS-CON SIR09P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1236',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8935' => [
            'name' => 'SIRGAS-CON SIR10P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1237',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8937' => [
            'name' => 'SIRGAS-CON SIR11P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1238',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8939' => [
            'name' => 'SIRGAS-CON SIR13P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1239',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8941' => [
            'name' => 'SIRGAS-CON SIR14P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1240',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8943' => [
            'name' => 'SIRGAS-CON SIR15P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1241',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8945' => [
            'name' => 'SIRGAS-CON SIR17P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1242',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8947' => [
            'name' => 'SIRGAS-Chile 2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1243',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9001' => [
            'name' => 'IGS97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1244',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9004' => [
            'name' => 'IGS00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1245',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9007' => [
            'name' => 'IGb00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1246',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9010' => [
            'name' => 'IGS05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1247',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9015' => [
            'name' => 'IGb08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1248',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9070' => [
            'name' => 'NAD83(MARP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1221',
            'extent' => ['4167'],
        ],
        'urn:ogc:def:crs:EPSG::9073' => [
            'name' => 'NAD83(PACP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1249',
            'extent' => ['4162'],
        ],
        'urn:ogc:def:crs:EPSG::9138' => [
            'name' => 'KOSOVAREF01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1251',
            'extent' => ['4542'],
        ],
        'urn:ogc:def:crs:EPSG::9146' => [
            'name' => 'SIRGAS-Chile 2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1252',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9151' => [
            'name' => 'SIRGAS-Chile 2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1253',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9266' => [
            'name' => 'MGI',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6312',
            'extent' => ['1037'],
        ],
        'urn:ogc:def:crs:EPSG::9292' => [
            'name' => 'ONGD17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1263',
            'extent' => ['1183'],
        ],
        'urn:ogc:def:crs:EPSG::9307' => [
            'name' => 'ATRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1291',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::9331' => [
            'name' => 'KSA-GRF17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1268',
            'extent' => ['1206'],
        ],
        'urn:ogc:def:crs:EPSG::9378' => [
            'name' => 'IGb14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1272',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9468' => [
            'name' => 'SRGI2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1293',
            'extent' => ['1122'],
        ],
        'urn:ogc:def:crs:EPSG::9545' => [
            'name' => 'LTF2004(G)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1295',
            'extent' => ['4613'],
        ],
        'urn:ogc:def:crs:EPSG::9694' => [
            'name' => 'REDGEOMIN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1304',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9700' => [
            'name' => 'ETRF2000-PL',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1305',
            'extent' => ['1192'],
        ],
        'urn:ogc:def:crs:EPSG::9753' => [
            'name' => 'WGS 84 (G2139)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1309',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9775' => [
            'name' => 'RGF93 v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1312',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9780' => [
            'name' => 'RGF93 v2b',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1313',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9892' => [
            'name' => 'LUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::6181',
            'extent' => ['1146'],
        ],
        'urn:ogc:def:crs:EPSG::9988' => [
            'name' => 'ITRF2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1322',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::10176' => [
            'name' => 'IGS20',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1333',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::20039' => [
            'name' => 'SIRGAS-Chile 2021',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1327',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::20044' => [
            'name' => 'MAGNA-SIRGAS 2018',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6500',
            'datum' => 'urn:ogc:def:datum:EPSG::1329',
            'extent' => ['1070'],
        ],
    ];
}
