<?php
/**
 * PHPCoord.
 *
 * @author Doug Wright
 */
declare(strict_types=1);

namespace PHPCoord\CoordinateReferenceSystem;

/**
 * @internal
 * This file contains the Geocentric 3D CRS SRID data, it only exists here because otherwise the main file becomes too large
 * for PHPStorm to analyse with its default settings and therefore the constants in it aren't available for
 * code-completion which defeats the whole point of having them...
 */
trait Geographic3DSRIDData
{
    protected static array $sridData = [
        'urn:ogc:def:crs:EPSG::3823' => [
            'name' => 'TWD97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::3822',
            'datum' => 'urn:ogc:def:datum:EPSG::1026',
            'extent' => ['1228'],
        ],
        'urn:ogc:def:crs:EPSG::3888' => [
            'name' => 'IGRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::3887',
            'datum' => 'urn:ogc:def:datum:EPSG::1029',
            'extent' => ['1124'],
        ],
        'urn:ogc:def:crs:EPSG::4017' => [
            'name' => 'MOLDREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4000',
            'datum' => 'urn:ogc:def:datum:EPSG::1032',
            'extent' => ['1162'],
        ],
        'urn:ogc:def:crs:EPSG::4040' => [
            'name' => 'RGRDC 2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4039',
            'datum' => 'urn:ogc:def:datum:EPSG::1033',
            'extent' => ['3613'],
        ],
        'urn:ogc:def:crs:EPSG::4074' => [
            'name' => 'SREF98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4073',
            'datum' => 'urn:ogc:def:datum:EPSG::1034',
            'extent' => ['4543'],
        ],
        'urn:ogc:def:crs:EPSG::4080' => [
            'name' => 'REGCAN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4079',
            'datum' => 'urn:ogc:def:datum:EPSG::1035',
            'extent' => ['3199'],
        ],
        'urn:ogc:def:crs:EPSG::4466' => [
            'name' => 'RGSPM06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4465',
            'datum' => 'urn:ogc:def:datum:EPSG::1038',
            'extent' => ['1220'],
        ],
        'urn:ogc:def:crs:EPSG::4469' => [
            'name' => 'RGM04',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4468',
            'datum' => 'urn:ogc:def:datum:EPSG::1036',
            'extent' => ['1159'],
        ],
        'urn:ogc:def:crs:EPSG::4472' => [
            'name' => 'Cadastre 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4473',
            'datum' => 'urn:ogc:def:datum:EPSG::1037',
            'extent' => ['3340'],
        ],
        'urn:ogc:def:crs:EPSG::4480' => [
            'name' => 'China Geodetic Coordinate System 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4479',
            'datum' => 'urn:ogc:def:datum:EPSG::1043',
            'extent' => ['1067'],
        ],
        'urn:ogc:def:crs:EPSG::4482' => [
            'name' => 'Mexico ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4481',
            'datum' => 'urn:ogc:def:datum:EPSG::1042',
            'extent' => ['1160'],
        ],
        'urn:ogc:def:crs:EPSG::4557' => [
            'name' => 'RRAF 1991',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4556',
            'datum' => 'urn:ogc:def:datum:EPSG::1047',
            'extent' => ['2824'],
        ],
        'urn:ogc:def:crs:EPSG::4883' => [
            'name' => 'Slovenia 1996',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4882',
            'datum' => 'urn:ogc:def:datum:EPSG::6765',
            'extent' => ['1212'],
        ],
        'urn:ogc:def:crs:EPSG::4885' => [
            'name' => 'RSRGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4884',
            'datum' => 'urn:ogc:def:datum:EPSG::6764',
            'extent' => ['3558'],
        ],
        'urn:ogc:def:crs:EPSG::4887' => [
            'name' => 'BDA2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4886',
            'datum' => 'urn:ogc:def:datum:EPSG::6762',
            'extent' => ['1047'],
        ],
        'urn:ogc:def:crs:EPSG::4889' => [
            'name' => 'HTRS96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4888',
            'datum' => 'urn:ogc:def:datum:EPSG::6761',
            'extent' => ['1076'],
        ],
        'urn:ogc:def:crs:EPSG::4891' => [
            'name' => 'WGS 66',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4890',
            'datum' => 'urn:ogc:def:datum:EPSG::6760',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4893' => [
            'name' => 'NAD83(NSRS2007)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4892',
            'datum' => 'urn:ogc:def:datum:EPSG::6759',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::4895' => [
            'name' => 'JAD2001',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4894',
            'datum' => 'urn:ogc:def:datum:EPSG::6758',
            'extent' => ['1128'],
        ],
        'urn:ogc:def:crs:EPSG::4898' => [
            'name' => 'DGN95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4897',
            'datum' => 'urn:ogc:def:datum:EPSG::6755',
            'extent' => ['1122'],
        ],
        'urn:ogc:def:crs:EPSG::4900' => [
            'name' => 'LGD2006',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4899',
            'datum' => 'urn:ogc:def:datum:EPSG::6754',
            'extent' => ['1143'],
        ],
        'urn:ogc:def:crs:EPSG::4907' => [
            'name' => 'RGNC91-93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4906',
            'datum' => 'urn:ogc:def:datum:EPSG::6749',
            'extent' => ['1174'],
        ],
        'urn:ogc:def:crs:EPSG::4909' => [
            'name' => 'GR96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4908',
            'datum' => 'urn:ogc:def:datum:EPSG::6747',
            'extent' => ['1107'],
        ],
        'urn:ogc:def:crs:EPSG::4921' => [
            'name' => 'GDM2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4920',
            'datum' => 'urn:ogc:def:datum:EPSG::6742',
            'extent' => ['1151'],
        ],
        'urn:ogc:def:crs:EPSG::4923' => [
            'name' => 'PZ-90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4922',
            'datum' => 'urn:ogc:def:datum:EPSG::6740',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4925' => [
            'name' => 'Mauritania 1999',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4924',
            'datum' => 'urn:ogc:def:datum:EPSG::6702',
            'extent' => ['1157'],
        ],
        'urn:ogc:def:crs:EPSG::4927' => [
            'name' => 'Korea 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4926',
            'datum' => 'urn:ogc:def:datum:EPSG::6737',
            'extent' => ['1135'],
        ],
        'urn:ogc:def:crs:EPSG::4929' => [
            'name' => 'POSGAR 94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4928',
            'datum' => 'urn:ogc:def:datum:EPSG::6694',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::4931' => [
            'name' => 'Australian Antarctic',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4930',
            'datum' => 'urn:ogc:def:datum:EPSG::6176',
            'extent' => ['1278'],
        ],
        'urn:ogc:def:crs:EPSG::4933' => [
            'name' => 'CHTRS95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4932',
            'datum' => 'urn:ogc:def:datum:EPSG::6151',
            'extent' => ['1286'],
        ],
        'urn:ogc:def:crs:EPSG::4935' => [
            'name' => 'EST97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4934',
            'datum' => 'urn:ogc:def:datum:EPSG::6180',
            'extent' => ['1090'],
        ],
        'urn:ogc:def:crs:EPSG::4937' => [
            'name' => 'ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4936',
            'datum' => 'urn:ogc:def:datum:EPSG::6258',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::4939' => [
            'name' => 'GDA94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4938',
            'datum' => 'urn:ogc:def:datum:EPSG::6283',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::4941' => [
            'name' => 'Hartebeesthoek94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4940',
            'datum' => 'urn:ogc:def:datum:EPSG::6148',
            'extent' => ['4540'],
        ],
        'urn:ogc:def:crs:EPSG::4943' => [
            'name' => 'IRENET95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4942',
            'datum' => 'urn:ogc:def:datum:EPSG::6173',
            'extent' => ['1305'],
        ],
        'urn:ogc:def:crs:EPSG::4945' => [
            'name' => 'ISN93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4944',
            'datum' => 'urn:ogc:def:datum:EPSG::6659',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::4947' => [
            'name' => 'JGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4946',
            'datum' => 'urn:ogc:def:datum:EPSG::6612',
            'extent' => ['1129'],
        ],
        'urn:ogc:def:crs:EPSG::4949' => [
            'name' => 'LKS92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4948',
            'datum' => 'urn:ogc:def:datum:EPSG::6661',
            'extent' => ['1139'],
        ],
        'urn:ogc:def:crs:EPSG::4951' => [
            'name' => 'LKS94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4950',
            'datum' => 'urn:ogc:def:datum:EPSG::6126',
            'extent' => ['1145'],
        ],
        'urn:ogc:def:crs:EPSG::4953' => [
            'name' => 'Moznet',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4952',
            'datum' => 'urn:ogc:def:datum:EPSG::6130',
            'extent' => ['1167'],
        ],
        'urn:ogc:def:crs:EPSG::4955' => [
            'name' => 'NAD83(CSRS)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4954',
            'datum' => 'urn:ogc:def:datum:EPSG::6140',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::4957' => [
            'name' => 'NAD83(HARN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4956',
            'datum' => 'urn:ogc:def:datum:EPSG::6152',
            'extent' => ['1337'],
        ],
        'urn:ogc:def:crs:EPSG::4959' => [
            'name' => 'NZGD2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4958',
            'datum' => 'urn:ogc:def:datum:EPSG::6167',
            'extent' => ['1175'],
        ],
        'urn:ogc:def:crs:EPSG::4961' => [
            'name' => 'POSGAR 98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4960',
            'datum' => 'urn:ogc:def:datum:EPSG::6190',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::4963' => [
            'name' => 'REGVEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4962',
            'datum' => 'urn:ogc:def:datum:EPSG::6189',
            'extent' => ['1251'],
        ],
        'urn:ogc:def:crs:EPSG::4965' => [
            'name' => 'RGF93 v1',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4964',
            'datum' => 'urn:ogc:def:datum:EPSG::6171',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::4967' => [
            'name' => 'RGFG95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4966',
            'datum' => 'urn:ogc:def:datum:EPSG::6624',
            'extent' => ['1097'],
        ],
        'urn:ogc:def:crs:EPSG::4971' => [
            'name' => 'RGR92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4970',
            'datum' => 'urn:ogc:def:datum:EPSG::6627',
            'extent' => ['3902'],
        ],
        'urn:ogc:def:crs:EPSG::4975' => [
            'name' => 'SIRGAS 1995',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4974',
            'datum' => 'urn:ogc:def:datum:EPSG::6170',
            'extent' => ['3448'],
        ],
        'urn:ogc:def:crs:EPSG::4977' => [
            'name' => 'SWEREF99',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4976',
            'datum' => 'urn:ogc:def:datum:EPSG::6619',
            'extent' => ['1225'],
        ],
        'urn:ogc:def:crs:EPSG::4979' => [
            'name' => 'WGS 84',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4978',
            'datum' => 'urn:ogc:def:datum:EPSG::6326',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4981' => [
            'name' => 'Yemen NGN96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4980',
            'datum' => 'urn:ogc:def:datum:EPSG::6163',
            'extent' => ['1257'],
        ],
        'urn:ogc:def:crs:EPSG::4983' => [
            'name' => 'IGM95',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4982',
            'datum' => 'urn:ogc:def:datum:EPSG::6670',
            'extent' => ['3343'],
        ],
        'urn:ogc:def:crs:EPSG::4985' => [
            'name' => 'WGS 72',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4984',
            'datum' => 'urn:ogc:def:datum:EPSG::6322',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4987' => [
            'name' => 'WGS 72BE',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4986',
            'datum' => 'urn:ogc:def:datum:EPSG::6324',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::4989' => [
            'name' => 'SIRGAS 2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4988',
            'datum' => 'urn:ogc:def:datum:EPSG::6674',
            'extent' => ['3418'],
        ],
        'urn:ogc:def:crs:EPSG::4991' => [
            'name' => 'Lao 1993',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4990',
            'datum' => 'urn:ogc:def:datum:EPSG::6677',
            'extent' => ['1138'],
        ],
        'urn:ogc:def:crs:EPSG::4993' => [
            'name' => 'Lao 1997',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4992',
            'datum' => 'urn:ogc:def:datum:EPSG::6678',
            'extent' => ['1138'],
        ],
        'urn:ogc:def:crs:EPSG::4995' => [
            'name' => 'PRS92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4994',
            'datum' => 'urn:ogc:def:datum:EPSG::6683',
            'extent' => ['1190'],
        ],
        'urn:ogc:def:crs:EPSG::4997' => [
            'name' => 'MAGNA-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4996',
            'datum' => 'urn:ogc:def:datum:EPSG::6686',
            'extent' => ['1070'],
        ],
        'urn:ogc:def:crs:EPSG::4999' => [
            'name' => 'RGPF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4998',
            'datum' => 'urn:ogc:def:datum:EPSG::6687',
            'extent' => ['1098'],
        ],
        'urn:ogc:def:crs:EPSG::5012' => [
            'name' => 'PTRA08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5011',
            'datum' => 'urn:ogc:def:datum:EPSG::1041',
            'extent' => ['3670'],
        ],
        'urn:ogc:def:crs:EPSG::5245' => [
            'name' => 'GDBD2009',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5244',
            'datum' => 'urn:ogc:def:datum:EPSG::1056',
            'extent' => ['1055'],
        ],
        'urn:ogc:def:crs:EPSG::5251' => [
            'name' => 'TUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5250',
            'datum' => 'urn:ogc:def:datum:EPSG::1057',
            'extent' => ['1237'],
        ],
        'urn:ogc:def:crs:EPSG::5263' => [
            'name' => 'DRUKREF 03',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5262',
            'datum' => 'urn:ogc:def:datum:EPSG::1058',
            'extent' => ['1048'],
        ],
        'urn:ogc:def:crs:EPSG::5323' => [
            'name' => 'ISN2004',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5322',
            'datum' => 'urn:ogc:def:datum:EPSG::1060',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::5342' => [
            'name' => 'POSGAR 2007',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5341',
            'datum' => 'urn:ogc:def:datum:EPSG::1062',
            'extent' => ['1033'],
        ],
        'urn:ogc:def:crs:EPSG::5353' => [
            'name' => 'MARGEN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5352',
            'datum' => 'urn:ogc:def:datum:EPSG::1063',
            'extent' => ['1049'],
        ],
        'urn:ogc:def:crs:EPSG::5359' => [
            'name' => 'SIRGAS-Chile 2002',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5358',
            'datum' => 'urn:ogc:def:datum:EPSG::1064',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::5364' => [
            'name' => 'CR05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5363',
            'datum' => 'urn:ogc:def:datum:EPSG::1065',
            'extent' => ['1074'],
        ],
        'urn:ogc:def:crs:EPSG::5370' => [
            'name' => 'MACARIO SOLIS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5368',
            'datum' => 'urn:ogc:def:datum:EPSG::1066',
            'extent' => ['1186'],
        ],
        'urn:ogc:def:crs:EPSG::5372' => [
            'name' => 'Peru96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5369',
            'datum' => 'urn:ogc:def:datum:EPSG::1067',
            'extent' => ['1189'],
        ],
        'urn:ogc:def:crs:EPSG::5380' => [
            'name' => 'SIRGAS-ROU98',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5379',
            'datum' => 'urn:ogc:def:datum:EPSG::1068',
            'extent' => ['1247'],
        ],
        'urn:ogc:def:crs:EPSG::5392' => [
            'name' => 'SIRGAS_ES2007.8',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5391',
            'datum' => 'urn:ogc:def:datum:EPSG::1069',
            'extent' => ['1087'],
        ],
        'urn:ogc:def:crs:EPSG::5488' => [
            'name' => 'RGAF09',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5487',
            'datum' => 'urn:ogc:def:datum:EPSG::1073',
            'extent' => ['2824'],
        ],
        'urn:ogc:def:crs:EPSG::5545' => [
            'name' => 'PNG94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5544',
            'datum' => 'urn:ogc:def:datum:EPSG::1076',
            'extent' => ['1187'],
        ],
        'urn:ogc:def:crs:EPSG::5560' => [
            'name' => 'UCS-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5558',
            'datum' => 'urn:ogc:def:datum:EPSG::1077',
            'extent' => ['1242'],
        ],
        'urn:ogc:def:crs:EPSG::5592' => [
            'name' => 'FEH2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5591',
            'datum' => 'urn:ogc:def:datum:EPSG::1078',
            'extent' => ['3889'],
        ],
        'urn:ogc:def:crs:EPSG::5830' => [
            'name' => 'DB_REF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5828',
            'datum' => 'urn:ogc:def:datum:EPSG::1081',
            'extent' => ['3339'],
        ],
        'urn:ogc:def:crs:EPSG::5885' => [
            'name' => 'TGD2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5884',
            'datum' => 'urn:ogc:def:datum:EPSG::1095',
            'extent' => ['1234'],
        ],
        'urn:ogc:def:crs:EPSG::6134' => [
            'name' => 'CIGD11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6133',
            'datum' => 'urn:ogc:def:datum:EPSG::1100',
            'extent' => ['1063'],
        ],
        'urn:ogc:def:crs:EPSG::6310' => [
            'name' => 'CGRS93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6309',
            'datum' => 'urn:ogc:def:datum:EPSG::1112',
            'extent' => ['3236'],
        ],
        'urn:ogc:def:crs:EPSG::6319' => [
            'name' => 'NAD83(2011)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6317',
            'datum' => 'urn:ogc:def:datum:EPSG::1116',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::6321' => [
            'name' => 'NAD83(PA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6320',
            'datum' => 'urn:ogc:def:datum:EPSG::1117',
            'extent' => ['4162'],
        ],
        'urn:ogc:def:crs:EPSG::6324' => [
            'name' => 'NAD83(MA11)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6323',
            'datum' => 'urn:ogc:def:datum:EPSG::1118',
            'extent' => ['4167'],
        ],
        'urn:ogc:def:crs:EPSG::6364' => [
            'name' => 'Mexico ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6363',
            'datum' => 'urn:ogc:def:datum:EPSG::1120',
            'extent' => ['1160'],
        ],
        'urn:ogc:def:crs:EPSG::6667' => [
            'name' => 'JGD2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6666',
            'datum' => 'urn:ogc:def:datum:EPSG::1128',
            'extent' => ['1129'],
        ],
        'urn:ogc:def:crs:EPSG::6705' => [
            'name' => 'RDN2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6704',
            'datum' => 'urn:ogc:def:datum:EPSG::1132',
            'extent' => ['3343'],
        ],
        'urn:ogc:def:crs:EPSG::6782' => [
            'name' => 'NAD83(CORS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6781',
            'datum' => 'urn:ogc:def:datum:EPSG::1133',
            'extent' => ['1511'],
        ],
        'urn:ogc:def:crs:EPSG::6982' => [
            'name' => 'IG05 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6981',
            'datum' => 'urn:ogc:def:datum:EPSG::1142',
            'extent' => ['2603'],
        ],
        'urn:ogc:def:crs:EPSG::6989' => [
            'name' => 'IG05/12 Intermediate CRS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6988',
            'datum' => 'urn:ogc:def:datum:EPSG::1144',
            'extent' => ['2603'],
        ],
        'urn:ogc:def:crs:EPSG::7034' => [
            'name' => 'RGSPM06 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4466',
            'datum' => 'urn:ogc:def:datum:EPSG::1038',
            'extent' => ['1220'],
        ],
        'urn:ogc:def:crs:EPSG::7036' => [
            'name' => 'RGR92 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4971',
            'datum' => 'urn:ogc:def:datum:EPSG::6627',
            'extent' => ['3902'],
        ],
        'urn:ogc:def:crs:EPSG::7038' => [
            'name' => 'RGM04 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4469',
            'datum' => 'urn:ogc:def:datum:EPSG::1036',
            'extent' => ['1159'],
        ],
        'urn:ogc:def:crs:EPSG::7040' => [
            'name' => 'RGFG95 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4967',
            'datum' => 'urn:ogc:def:datum:EPSG::6624',
            'extent' => ['1097'],
        ],
        'urn:ogc:def:crs:EPSG::7042' => [
            'name' => 'RGF93 v1 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4965',
            'datum' => 'urn:ogc:def:datum:EPSG::6171',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::7072' => [
            'name' => 'RGTAAF07',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7071',
            'datum' => 'urn:ogc:def:datum:EPSG::1113',
            'extent' => ['4246'],
        ],
        'urn:ogc:def:crs:EPSG::7085' => [
            'name' => 'RGAF09 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5488',
            'datum' => 'urn:ogc:def:datum:EPSG::1073',
            'extent' => ['2824'],
        ],
        'urn:ogc:def:crs:EPSG::7087' => [
            'name' => 'RGTAAF07 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7072',
            'datum' => 'urn:ogc:def:datum:EPSG::1113',
            'extent' => ['4246'],
        ],
        'urn:ogc:def:crs:EPSG::7135' => [
            'name' => 'IGD05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7134',
            'datum' => 'urn:ogc:def:datum:EPSG::1114',
            'extent' => ['1126'],
        ],
        'urn:ogc:def:crs:EPSG::7138' => [
            'name' => 'IGD05/12',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7137',
            'datum' => 'urn:ogc:def:datum:EPSG::1115',
            'extent' => ['1126'],
        ],
        'urn:ogc:def:crs:EPSG::7372' => [
            'name' => 'ONGD14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7371',
            'datum' => 'urn:ogc:def:datum:EPSG::1147',
            'extent' => ['1183'],
        ],
        'urn:ogc:def:crs:EPSG::7657' => [
            'name' => 'WGS 84 (G730)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7656',
            'datum' => 'urn:ogc:def:datum:EPSG::1152',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7659' => [
            'name' => 'WGS 84 (G873)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7658',
            'datum' => 'urn:ogc:def:datum:EPSG::1153',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7661' => [
            'name' => 'WGS 84 (G1150)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7660',
            'datum' => 'urn:ogc:def:datum:EPSG::1154',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7663' => [
            'name' => 'WGS 84 (G1674)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7662',
            'datum' => 'urn:ogc:def:datum:EPSG::1155',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7665' => [
            'name' => 'WGS 84 (G1762)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7664',
            'datum' => 'urn:ogc:def:datum:EPSG::1156',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7678' => [
            'name' => 'PZ-90.02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7677',
            'datum' => 'urn:ogc:def:datum:EPSG::1157',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7680' => [
            'name' => 'PZ-90.11',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7679',
            'datum' => 'urn:ogc:def:datum:EPSG::1158',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7682' => [
            'name' => 'GSK-2011',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7681',
            'datum' => 'urn:ogc:def:datum:EPSG::1159',
            'extent' => ['1198'],
        ],
        'urn:ogc:def:crs:EPSG::7685' => [
            'name' => 'Kyrg-06',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7684',
            'datum' => 'urn:ogc:def:datum:EPSG::1160',
            'extent' => ['1137'],
        ],
        'urn:ogc:def:crs:EPSG::7797' => [
            'name' => 'BGS2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7796',
            'datum' => 'urn:ogc:def:datum:EPSG::1167',
            'extent' => ['1056'],
        ],
        'urn:ogc:def:crs:EPSG::7816' => [
            'name' => 'WGS 84 (Transit)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7815',
            'datum' => 'urn:ogc:def:datum:EPSG::1166',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7843' => [
            'name' => 'GDA2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7842',
            'datum' => 'urn:ogc:def:datum:EPSG::1168',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::7880' => [
            'name' => 'St. Helena Tritan',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7879',
            'datum' => 'urn:ogc:def:datum:EPSG::1173',
            'extent' => ['3183'],
        ],
        'urn:ogc:def:crs:EPSG::7885' => [
            'name' => 'SHGD2015',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7884',
            'datum' => 'urn:ogc:def:datum:EPSG::1174',
            'extent' => ['3183'],
        ],
        'urn:ogc:def:crs:EPSG::7900' => [
            'name' => 'ITRF88',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4910',
            'datum' => 'urn:ogc:def:datum:EPSG::6647',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7901' => [
            'name' => 'ITRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4911',
            'datum' => 'urn:ogc:def:datum:EPSG::6648',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7902' => [
            'name' => 'ITRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4912',
            'datum' => 'urn:ogc:def:datum:EPSG::6649',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7903' => [
            'name' => 'ITRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4913',
            'datum' => 'urn:ogc:def:datum:EPSG::6650',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7904' => [
            'name' => 'ITRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4914',
            'datum' => 'urn:ogc:def:datum:EPSG::6651',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7905' => [
            'name' => 'ITRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4915',
            'datum' => 'urn:ogc:def:datum:EPSG::6652',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7906' => [
            'name' => 'ITRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4916',
            'datum' => 'urn:ogc:def:datum:EPSG::6653',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7907' => [
            'name' => 'ITRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4917',
            'datum' => 'urn:ogc:def:datum:EPSG::6654',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7908' => [
            'name' => 'ITRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4918',
            'datum' => 'urn:ogc:def:datum:EPSG::6655',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7909' => [
            'name' => 'ITRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4919',
            'datum' => 'urn:ogc:def:datum:EPSG::6656',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7910' => [
            'name' => 'ITRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::4896',
            'datum' => 'urn:ogc:def:datum:EPSG::6896',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7911' => [
            'name' => 'ITRF2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::5332',
            'datum' => 'urn:ogc:def:datum:EPSG::1061',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7912' => [
            'name' => 'ITRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7789',
            'datum' => 'urn:ogc:def:datum:EPSG::1165',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::7915' => [
            'name' => 'ETRF89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7914',
            'datum' => 'urn:ogc:def:datum:EPSG::1178',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7917' => [
            'name' => 'ETRF90',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7916',
            'datum' => 'urn:ogc:def:datum:EPSG::1179',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7919' => [
            'name' => 'ETRF91',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7918',
            'datum' => 'urn:ogc:def:datum:EPSG::1180',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7921' => [
            'name' => 'ETRF92',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7920',
            'datum' => 'urn:ogc:def:datum:EPSG::1181',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7923' => [
            'name' => 'ETRF93',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7922',
            'datum' => 'urn:ogc:def:datum:EPSG::1182',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7925' => [
            'name' => 'ETRF94',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7924',
            'datum' => 'urn:ogc:def:datum:EPSG::1183',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7927' => [
            'name' => 'ETRF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7926',
            'datum' => 'urn:ogc:def:datum:EPSG::1184',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7929' => [
            'name' => 'ETRF97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7928',
            'datum' => 'urn:ogc:def:datum:EPSG::1185',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::7931' => [
            'name' => 'ETRF2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::7930',
            'datum' => 'urn:ogc:def:datum:EPSG::1186',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8085' => [
            'name' => 'ISN2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8084',
            'datum' => 'urn:ogc:def:datum:EPSG::1187',
            'extent' => ['1120'],
        ],
        'urn:ogc:def:crs:EPSG::8231' => [
            'name' => 'NAD83(CSRS96)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8230',
            'datum' => 'urn:ogc:def:datum:EPSG::1192',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8235' => [
            'name' => 'NAD83(CSRS)v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8233',
            'datum' => 'urn:ogc:def:datum:EPSG::1193',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8239' => [
            'name' => 'NAD83(CSRS)v3',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8238',
            'datum' => 'urn:ogc:def:datum:EPSG::1194',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8244' => [
            'name' => 'NAD83(CSRS)v4',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8242',
            'datum' => 'urn:ogc:def:datum:EPSG::1195',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8248' => [
            'name' => 'NAD83(CSRS)v5',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8247',
            'datum' => 'urn:ogc:def:datum:EPSG::1196',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8251' => [
            'name' => 'NAD83(CSRS)v6',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8250',
            'datum' => 'urn:ogc:def:datum:EPSG::1197',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8254' => [
            'name' => 'NAD83(CSRS)v7',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8253',
            'datum' => 'urn:ogc:def:datum:EPSG::1198',
            'extent' => ['1061'],
        ],
        'urn:ogc:def:crs:EPSG::8399' => [
            'name' => 'ETRF2005',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8397',
            'datum' => 'urn:ogc:def:datum:EPSG::1204',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8403' => [
            'name' => 'ETRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8401',
            'datum' => 'urn:ogc:def:datum:EPSG::1206',
            'extent' => ['1298'],
        ],
        'urn:ogc:def:crs:EPSG::8426' => [
            'name' => 'Hong Kong Geodetic CS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8425',
            'datum' => 'urn:ogc:def:datum:EPSG::1209',
            'extent' => ['1118'],
        ],
        'urn:ogc:def:crs:EPSG::8430' => [
            'name' => 'Macao 2008',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8429',
            'datum' => 'urn:ogc:def:datum:EPSG::1208',
            'extent' => ['1147'],
        ],
        'urn:ogc:def:crs:EPSG::8542' => [
            'name' => 'NAD83(FBN)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8541',
            'datum' => 'urn:ogc:def:datum:EPSG::1211',
            'extent' => ['4515'],
        ],
        'urn:ogc:def:crs:EPSG::8544' => [
            'name' => 'NAD83(HARN Corrected)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8543',
            'datum' => 'urn:ogc:def:datum:EPSG::1212',
            'extent' => ['3634'],
        ],
        'urn:ogc:def:crs:EPSG::8684' => [
            'name' => 'SRB_ETRS89',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8683',
            'datum' => 'urn:ogc:def:datum:EPSG::1214',
            'extent' => ['4543'],
        ],
        'urn:ogc:def:crs:EPSG::8698' => [
            'name' => 'RSAO13',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8697',
            'datum' => 'urn:ogc:def:datum:EPSG::1220',
            'extent' => ['1029'],
        ],
        'urn:ogc:def:crs:EPSG::8817' => [
            'name' => 'MTRF-2000',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8816',
            'datum' => 'urn:ogc:def:datum:EPSG::1218',
            'extent' => ['1206'],
        ],
        'urn:ogc:def:crs:EPSG::8899' => [
            'name' => 'RGWF96',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8898',
            'datum' => 'urn:ogc:def:datum:EPSG::1223',
            'extent' => ['1255'],
        ],
        'urn:ogc:def:crs:EPSG::8901' => [
            'name' => 'RGWF96 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8899',
            'datum' => 'urn:ogc:def:datum:EPSG::1223',
            'extent' => ['1255'],
        ],
        'urn:ogc:def:crs:EPSG::8906' => [
            'name' => 'CR-SIRGAS',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8905',
            'datum' => 'urn:ogc:def:datum:EPSG::1225',
            'extent' => ['1074'],
        ],
        'urn:ogc:def:crs:EPSG::8916' => [
            'name' => 'SIRGAS-CON DGF00P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8915',
            'datum' => 'urn:ogc:def:datum:EPSG::1227',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8918' => [
            'name' => 'SIRGAS-CON DGF01P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8917',
            'datum' => 'urn:ogc:def:datum:EPSG::1228',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8920' => [
            'name' => 'SIRGAS-CON DGF01P02',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8919',
            'datum' => 'urn:ogc:def:datum:EPSG::1229',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8922' => [
            'name' => 'SIRGAS-CON DGF02P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8921',
            'datum' => 'urn:ogc:def:datum:EPSG::1230',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8924' => [
            'name' => 'SIRGAS-CON DGF04P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8923',
            'datum' => 'urn:ogc:def:datum:EPSG::1231',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8926' => [
            'name' => 'SIRGAS-CON DGF05P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8925',
            'datum' => 'urn:ogc:def:datum:EPSG::1232',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8928' => [
            'name' => 'SIRGAS-CON DGF06P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8927',
            'datum' => 'urn:ogc:def:datum:EPSG::1233',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8930' => [
            'name' => 'SIRGAS-CON DGF07P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8929',
            'datum' => 'urn:ogc:def:datum:EPSG::1234',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8932' => [
            'name' => 'SIRGAS-CON DGF08P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8931',
            'datum' => 'urn:ogc:def:datum:EPSG::1235',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8934' => [
            'name' => 'SIRGAS-CON SIR09P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8933',
            'datum' => 'urn:ogc:def:datum:EPSG::1236',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8936' => [
            'name' => 'SIRGAS-CON SIR10P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8935',
            'datum' => 'urn:ogc:def:datum:EPSG::1237',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8938' => [
            'name' => 'SIRGAS-CON SIR11P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8937',
            'datum' => 'urn:ogc:def:datum:EPSG::1238',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8940' => [
            'name' => 'SIRGAS-CON SIR13P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8939',
            'datum' => 'urn:ogc:def:datum:EPSG::1239',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8942' => [
            'name' => 'SIRGAS-CON SIR14P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8941',
            'datum' => 'urn:ogc:def:datum:EPSG::1240',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8944' => [
            'name' => 'SIRGAS-CON SIR15P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8943',
            'datum' => 'urn:ogc:def:datum:EPSG::1241',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8946' => [
            'name' => 'SIRGAS-CON SIR17P01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8945',
            'datum' => 'urn:ogc:def:datum:EPSG::1242',
            'extent' => ['4530'],
        ],
        'urn:ogc:def:crs:EPSG::8948' => [
            'name' => 'SIRGAS-Chile 2010',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8947',
            'datum' => 'urn:ogc:def:datum:EPSG::1243',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9002' => [
            'name' => 'IGS97',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9001',
            'datum' => 'urn:ogc:def:datum:EPSG::1244',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9005' => [
            'name' => 'IGS00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9004',
            'datum' => 'urn:ogc:def:datum:EPSG::1245',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9008' => [
            'name' => 'IGb00',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9007',
            'datum' => 'urn:ogc:def:datum:EPSG::1246',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9011' => [
            'name' => 'IGS05',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9010',
            'datum' => 'urn:ogc:def:datum:EPSG::1247',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9013' => [
            'name' => 'IGS08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::6934',
            'datum' => 'urn:ogc:def:datum:EPSG::1141',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9016' => [
            'name' => 'IGb08',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9015',
            'datum' => 'urn:ogc:def:datum:EPSG::1248',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9018' => [
            'name' => 'IGS14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::8227',
            'datum' => 'urn:ogc:def:datum:EPSG::1191',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9071' => [
            'name' => 'NAD83(MARP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9070',
            'datum' => 'urn:ogc:def:datum:EPSG::1221',
            'extent' => ['4167'],
        ],
        'urn:ogc:def:crs:EPSG::9074' => [
            'name' => 'NAD83(PACP00)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9073',
            'datum' => 'urn:ogc:def:datum:EPSG::1249',
            'extent' => ['4162'],
        ],
        'urn:ogc:def:crs:EPSG::9139' => [
            'name' => 'KOSOVAREF01',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9138',
            'datum' => 'urn:ogc:def:datum:EPSG::1251',
            'extent' => ['4542'],
        ],
        'urn:ogc:def:crs:EPSG::9147' => [
            'name' => 'SIRGAS-Chile 2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9146',
            'datum' => 'urn:ogc:def:datum:EPSG::1252',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9152' => [
            'name' => 'SIRGAS-Chile 2016',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9151',
            'datum' => 'urn:ogc:def:datum:EPSG::1253',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9267' => [
            'name' => 'MGI',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9266',
            'datum' => 'urn:ogc:def:datum:EPSG::6312',
            'extent' => ['1037'],
        ],
        'urn:ogc:def:crs:EPSG::9293' => [
            'name' => 'ONGD17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9292',
            'datum' => 'urn:ogc:def:datum:EPSG::1263',
            'extent' => ['1183'],
        ],
        'urn:ogc:def:crs:EPSG::9308' => [
            'name' => 'ATRF2014',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9307',
            'datum' => 'urn:ogc:def:datum:EPSG::1291',
            'extent' => ['4177'],
        ],
        'urn:ogc:def:crs:EPSG::9332' => [
            'name' => 'KSA-GRF17',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9331',
            'datum' => 'urn:ogc:def:datum:EPSG::1268',
            'extent' => ['1206'],
        ],
        'urn:ogc:def:crs:EPSG::9379' => [
            'name' => 'IGb14',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9378',
            'datum' => 'urn:ogc:def:datum:EPSG::1272',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9469' => [
            'name' => 'SRGI2013',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9468',
            'datum' => 'urn:ogc:def:datum:EPSG::1293',
            'extent' => ['1122'],
        ],
        'urn:ogc:def:crs:EPSG::9546' => [
            'name' => 'LTF2004(G)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9545',
            'datum' => 'urn:ogc:def:datum:EPSG::1295',
            'extent' => ['4613'],
        ],
        'urn:ogc:def:crs:EPSG::9695' => [
            'name' => 'REDGEOMIN',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9694',
            'datum' => 'urn:ogc:def:datum:EPSG::1304',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::9701' => [
            'name' => 'ETRF2000-PL',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9700',
            'datum' => 'urn:ogc:def:datum:EPSG::1305',
            'extent' => ['1192'],
        ],
        'urn:ogc:def:crs:EPSG::9754' => [
            'name' => 'WGS 84 (G2139)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9753',
            'datum' => 'urn:ogc:def:datum:EPSG::1309',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::9776' => [
            'name' => 'RGF93 v2',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9775',
            'datum' => 'urn:ogc:def:datum:EPSG::1312',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9778' => [
            'name' => 'RGF93 v2 (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9776',
            'datum' => 'urn:ogc:def:datum:EPSG::1312',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9781' => [
            'name' => 'RGF93 v2b',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9780',
            'datum' => 'urn:ogc:def:datum:EPSG::1313',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9783' => [
            'name' => 'RGF93 v2b (lon-lat)',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6426',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9781',
            'datum' => 'urn:ogc:def:datum:EPSG::1313',
            'extent' => ['1096'],
        ],
        'urn:ogc:def:crs:EPSG::9893' => [
            'name' => 'LUREF',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9892',
            'datum' => 'urn:ogc:def:datum:EPSG::6181',
            'extent' => ['1146'],
        ],
        'urn:ogc:def:crs:EPSG::9989' => [
            'name' => 'ITRF2020',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::9988',
            'datum' => 'urn:ogc:def:datum:EPSG::1322',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::10177' => [
            'name' => 'IGS20',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::10176',
            'datum' => 'urn:ogc:def:datum:EPSG::1333',
            'extent' => ['1262'],
        ],
        'urn:ogc:def:crs:EPSG::20040' => [
            'name' => 'SIRGAS-Chile 2021',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::20039',
            'datum' => 'urn:ogc:def:datum:EPSG::1327',
            'extent' => ['1066'],
        ],
        'urn:ogc:def:crs:EPSG::20045' => [
            'name' => 'MAGNA-SIRGAS 2018',
            'coordinate_system' => 'urn:ogc:def:cs:EPSG::6423',
            'base_crs' => 'urn:ogc:def:crs:EPSG::20044',
            'datum' => 'urn:ogc:def:datum:EPSG::1329',
            'extent' => ['1070'],
        ],
    ];
}
